// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v05-constraint-vocabulary.proto
// Protobuf Java Version: 4.29.3

package vcb.ca;

public final class V05ConstraintVocabulary {
  private V05ConstraintVocabulary() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      V05ConstraintVocabulary.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(vcb.ca.V05ConstraintVocabulary.sk);
    registry.add(vcb.ca.V05ConstraintVocabulary.mk);
    registry.add(vcb.ca.V05ConstraintVocabulary.fk);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConstraintAnnotationsVocabularyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vcb.ca.ConstraintAnnotationsVocabulary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * - Keywords applicable to any properties
     * </pre>
     *
     * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the enum field is set.
     */
    boolean hasEnum();
    /**
     * <pre>
     * - Keywords applicable to any properties
     * </pre>
     *
     * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The enum.
     */
    java.lang.String getEnum();
    /**
     * <pre>
     * - Keywords applicable to any properties
     * </pre>
     *
     * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for enum.
     */
    com.google.protobuf.ByteString
        getEnumBytes();

    /**
     * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the const field is set.
     */
    boolean hasConst();
    /**
     * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The const.
     */
    java.lang.String getConst();
    /**
     * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for const.
     */
    com.google.protobuf.ByteString
        getConstBytes();

    /**
     * <pre>
     * - Keywords applicable to numeric properties
     * </pre>
     *
     * <code>optional int32 multipleOf = 56200 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the multipleOf field is set.
     */
    boolean hasMultipleOf();
    /**
     * <pre>
     * - Keywords applicable to numeric properties
     * </pre>
     *
     * <code>optional int32 multipleOf = 56200 [targets = TARGET_TYPE_FIELD];</code>
     * @return The multipleOf.
     */
    int getMultipleOf();

    /**
     * <code>optional int32 maximum = 56201 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maximum field is set.
     */
    boolean hasMaximum();
    /**
     * <code>optional int32 maximum = 56201 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maximum.
     */
    int getMaximum();

    /**
     * <code>optional int32 exclusiveMaximum = 56202 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the exclusiveMaximum field is set.
     */
    boolean hasExclusiveMaximum();
    /**
     * <code>optional int32 exclusiveMaximum = 56202 [targets = TARGET_TYPE_FIELD];</code>
     * @return The exclusiveMaximum.
     */
    int getExclusiveMaximum();

    /**
     * <code>optional int32 minimum = 56203 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the minimum field is set.
     */
    boolean hasMinimum();
    /**
     * <code>optional int32 minimum = 56203 [targets = TARGET_TYPE_FIELD];</code>
     * @return The minimum.
     */
    int getMinimum();

    /**
     * <code>optional int32 exclusiveMinimum = 56204 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the exclusiveMinimum field is set.
     */
    boolean hasExclusiveMinimum();
    /**
     * <code>optional int32 exclusiveMinimum = 56204 [targets = TARGET_TYPE_FIELD];</code>
     * @return The exclusiveMinimum.
     */
    int getExclusiveMinimum();

    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional int32 maxLength = 56400 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maxLength field is set.
     */
    boolean hasMaxLength();
    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional int32 maxLength = 56400 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maxLength.
     */
    int getMaxLength();

    /**
     * <code>optional int32 minLength = 56401 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the minLength field is set.
     */
    boolean hasMinLength();
    /**
     * <code>optional int32 minLength = 56401 [targets = TARGET_TYPE_FIELD];</code>
     * @return The minLength.
     */
    int getMinLength();

    /**
     * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the pattern field is set.
     */
    boolean hasPattern();
    /**
     * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
     * @return The pattern.
     */
    java.lang.String getPattern();
    /**
     * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for pattern.
     */
    com.google.protobuf.ByteString
        getPatternBytes();

    /**
     * <pre>
     * - Keywords applicable to array properties
     * </pre>
     *
     * <code>optional int32 maxItems = 56600 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maxItems field is set.
     */
    boolean hasMaxItems();
    /**
     * <pre>
     * - Keywords applicable to array properties
     * </pre>
     *
     * <code>optional int32 maxItems = 56600 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maxItems.
     */
    int getMaxItems();

    /**
     * <code>optional int32 minItems = 56601 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the minItems field is set.
     */
    boolean hasMinItems();
    /**
     * <code>optional int32 minItems = 56601 [targets = TARGET_TYPE_FIELD];</code>
     * @return The minItems.
     */
    int getMinItems();

    /**
     * <pre>
     * - Keywords applicable to object properties 
     * </pre>
     *
     * <code>optional int32 maxProperties = 56800 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maxProperties field is set.
     */
    boolean hasMaxProperties();
    /**
     * <pre>
     * - Keywords applicable to object properties 
     * </pre>
     *
     * <code>optional int32 maxProperties = 56800 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maxProperties.
     */
    int getMaxProperties();

    /**
     * <code>optional int32 maximinPropertiesmum = 56801 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maximinPropertiesmum field is set.
     */
    boolean hasMaximinPropertiesmum();
    /**
     * <code>optional int32 maximinPropertiesmum = 56801 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maximinPropertiesmum.
     */
    int getMaximinPropertiesmum();

    /**
     * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the required field is set.
     */
    boolean hasRequired();
    /**
     * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
     * @return The required.
     */
    java.lang.String getRequired();
    /**
     * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for required.
     */
    com.google.protobuf.ByteString
        getRequiredBytes();

    /**
     * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the dependentRequired field is set.
     */
    boolean hasDependentRequired();
    /**
     * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
     * @return The dependentRequired.
     */
    java.lang.String getDependentRequired();
    /**
     * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for dependentRequired.
     */
    com.google.protobuf.ByteString
        getDependentRequiredBytes();
  }
  /**
   * <pre>
   * *
   * Constraint Annotations Vocabulary Proto
   * (Version 1.0.0-DRAFT)
   *
   * The Constraint Annotations Vocabulary, defined as an extension of the SAS, provides commonly used metadata for 
   * annotating schemas at a physical level. Sometime is necessary to enable the consumption of data from the underlying 
   * datastore to expose these information. If this is not the case this information SHOULD not be exposed in order to hide 
   * to the consumer internal implementation details.
   *
   * Vocabulary url: 
   * - https://dpds.opendatamesh.org/specifications/sas/1.0.0-DRAFT/vocab/constraints/
   *
   * Authors: 
   * - Andrea Gioia
   *
   * LICENCE: 
   * - Apache License Version 2.0 (https://github.com/opendatamesh-initiative/odm-specification-schema-annotations/blob/main/LICENSE)
   * </pre>
   *
   * Protobuf type {@code vcb.ca.ConstraintAnnotationsVocabulary}
   */
  public static final class ConstraintAnnotationsVocabulary extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vcb.ca.ConstraintAnnotationsVocabulary)
      ConstraintAnnotationsVocabularyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ConstraintAnnotationsVocabulary.class.getName());
    }
    // Use ConstraintAnnotationsVocabulary.newBuilder() to construct.
    private ConstraintAnnotationsVocabulary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ConstraintAnnotationsVocabulary() {
      enum_ = "";
      const_ = "";
      pattern_ = "";
      required_ = "";
      dependentRequired_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vcb.ca.V05ConstraintVocabulary.internal_static_vcb_ca_ConstraintAnnotationsVocabulary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vcb.ca.V05ConstraintVocabulary.internal_static_vcb_ca_ConstraintAnnotationsVocabulary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.class, vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.Builder.class);
    }

    private int bitField0_;
    public static final int ENUM_FIELD_NUMBER = 56000;
    @SuppressWarnings("serial")
    private volatile java.lang.Object enum_ = "";
    /**
     * <pre>
     * - Keywords applicable to any properties
     * </pre>
     *
     * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the enum field is set.
     */
    @java.lang.Override
    public boolean hasEnum() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * - Keywords applicable to any properties
     * </pre>
     *
     * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The enum.
     */
    @java.lang.Override
    public java.lang.String getEnum() {
      java.lang.Object ref = enum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        enum_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * - Keywords applicable to any properties
     * </pre>
     *
     * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for enum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEnumBytes() {
      java.lang.Object ref = enum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONST_FIELD_NUMBER = 56001;
    @SuppressWarnings("serial")
    private volatile java.lang.Object const_ = "";
    /**
     * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the const field is set.
     */
    @java.lang.Override
    public boolean hasConst() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The const.
     */
    @java.lang.Override
    public java.lang.String getConst() {
      java.lang.Object ref = const_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        const_ = s;
        return s;
      }
    }
    /**
     * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for const.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConstBytes() {
      java.lang.Object ref = const_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        const_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MULTIPLEOF_FIELD_NUMBER = 56200;
    private int multipleOf_ = 0;
    /**
     * <pre>
     * - Keywords applicable to numeric properties
     * </pre>
     *
     * <code>optional int32 multipleOf = 56200 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the multipleOf field is set.
     */
    @java.lang.Override
    public boolean hasMultipleOf() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * - Keywords applicable to numeric properties
     * </pre>
     *
     * <code>optional int32 multipleOf = 56200 [targets = TARGET_TYPE_FIELD];</code>
     * @return The multipleOf.
     */
    @java.lang.Override
    public int getMultipleOf() {
      return multipleOf_;
    }

    public static final int MAXIMUM_FIELD_NUMBER = 56201;
    private int maximum_ = 0;
    /**
     * <code>optional int32 maximum = 56201 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maximum field is set.
     */
    @java.lang.Override
    public boolean hasMaximum() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 maximum = 56201 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maximum.
     */
    @java.lang.Override
    public int getMaximum() {
      return maximum_;
    }

    public static final int EXCLUSIVEMAXIMUM_FIELD_NUMBER = 56202;
    private int exclusiveMaximum_ = 0;
    /**
     * <code>optional int32 exclusiveMaximum = 56202 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the exclusiveMaximum field is set.
     */
    @java.lang.Override
    public boolean hasExclusiveMaximum() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 exclusiveMaximum = 56202 [targets = TARGET_TYPE_FIELD];</code>
     * @return The exclusiveMaximum.
     */
    @java.lang.Override
    public int getExclusiveMaximum() {
      return exclusiveMaximum_;
    }

    public static final int MINIMUM_FIELD_NUMBER = 56203;
    private int minimum_ = 0;
    /**
     * <code>optional int32 minimum = 56203 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the minimum field is set.
     */
    @java.lang.Override
    public boolean hasMinimum() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 minimum = 56203 [targets = TARGET_TYPE_FIELD];</code>
     * @return The minimum.
     */
    @java.lang.Override
    public int getMinimum() {
      return minimum_;
    }

    public static final int EXCLUSIVEMINIMUM_FIELD_NUMBER = 56204;
    private int exclusiveMinimum_ = 0;
    /**
     * <code>optional int32 exclusiveMinimum = 56204 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the exclusiveMinimum field is set.
     */
    @java.lang.Override
    public boolean hasExclusiveMinimum() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 exclusiveMinimum = 56204 [targets = TARGET_TYPE_FIELD];</code>
     * @return The exclusiveMinimum.
     */
    @java.lang.Override
    public int getExclusiveMinimum() {
      return exclusiveMinimum_;
    }

    public static final int MAXLENGTH_FIELD_NUMBER = 56400;
    private int maxLength_ = 0;
    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional int32 maxLength = 56400 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maxLength field is set.
     */
    @java.lang.Override
    public boolean hasMaxLength() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional int32 maxLength = 56400 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maxLength.
     */
    @java.lang.Override
    public int getMaxLength() {
      return maxLength_;
    }

    public static final int MINLENGTH_FIELD_NUMBER = 56401;
    private int minLength_ = 0;
    /**
     * <code>optional int32 minLength = 56401 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the minLength field is set.
     */
    @java.lang.Override
    public boolean hasMinLength() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int32 minLength = 56401 [targets = TARGET_TYPE_FIELD];</code>
     * @return The minLength.
     */
    @java.lang.Override
    public int getMinLength() {
      return minLength_;
    }

    public static final int PATTERN_FIELD_NUMBER = 56402;
    @SuppressWarnings("serial")
    private volatile java.lang.Object pattern_ = "";
    /**
     * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the pattern field is set.
     */
    @java.lang.Override
    public boolean hasPattern() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
     * @return The pattern.
     */
    @java.lang.Override
    public java.lang.String getPattern() {
      java.lang.Object ref = pattern_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pattern_ = s;
        return s;
      }
    }
    /**
     * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for pattern.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPatternBytes() {
      java.lang.Object ref = pattern_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pattern_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAXITEMS_FIELD_NUMBER = 56600;
    private int maxItems_ = 0;
    /**
     * <pre>
     * - Keywords applicable to array properties
     * </pre>
     *
     * <code>optional int32 maxItems = 56600 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maxItems field is set.
     */
    @java.lang.Override
    public boolean hasMaxItems() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     * - Keywords applicable to array properties
     * </pre>
     *
     * <code>optional int32 maxItems = 56600 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maxItems.
     */
    @java.lang.Override
    public int getMaxItems() {
      return maxItems_;
    }

    public static final int MINITEMS_FIELD_NUMBER = 56601;
    private int minItems_ = 0;
    /**
     * <code>optional int32 minItems = 56601 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the minItems field is set.
     */
    @java.lang.Override
    public boolean hasMinItems() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional int32 minItems = 56601 [targets = TARGET_TYPE_FIELD];</code>
     * @return The minItems.
     */
    @java.lang.Override
    public int getMinItems() {
      return minItems_;
    }

    public static final int MAXPROPERTIES_FIELD_NUMBER = 56800;
    private int maxProperties_ = 0;
    /**
     * <pre>
     * - Keywords applicable to object properties 
     * </pre>
     *
     * <code>optional int32 maxProperties = 56800 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maxProperties field is set.
     */
    @java.lang.Override
    public boolean hasMaxProperties() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <pre>
     * - Keywords applicable to object properties 
     * </pre>
     *
     * <code>optional int32 maxProperties = 56800 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maxProperties.
     */
    @java.lang.Override
    public int getMaxProperties() {
      return maxProperties_;
    }

    public static final int MAXIMINPROPERTIESMUM_FIELD_NUMBER = 56801;
    private int maximinPropertiesmum_ = 0;
    /**
     * <code>optional int32 maximinPropertiesmum = 56801 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the maximinPropertiesmum field is set.
     */
    @java.lang.Override
    public boolean hasMaximinPropertiesmum() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>optional int32 maximinPropertiesmum = 56801 [targets = TARGET_TYPE_FIELD];</code>
     * @return The maximinPropertiesmum.
     */
    @java.lang.Override
    public int getMaximinPropertiesmum() {
      return maximinPropertiesmum_;
    }

    public static final int REQUIRED_FIELD_NUMBER = 56802;
    @SuppressWarnings("serial")
    private volatile java.lang.Object required_ = "";
    /**
     * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the required field is set.
     */
    @java.lang.Override
    public boolean hasRequired() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
     * @return The required.
     */
    @java.lang.Override
    public java.lang.String getRequired() {
      java.lang.Object ref = required_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        required_ = s;
        return s;
      }
    }
    /**
     * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for required.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequiredBytes() {
      java.lang.Object ref = required_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        required_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPENDENTREQUIRED_FIELD_NUMBER = 56803;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dependentRequired_ = "";
    /**
     * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the dependentRequired field is set.
     */
    @java.lang.Override
    public boolean hasDependentRequired() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
     * @return The dependentRequired.
     */
    @java.lang.Override
    public java.lang.String getDependentRequired() {
      java.lang.Object ref = dependentRequired_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dependentRequired_ = s;
        return s;
      }
    }
    /**
     * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for dependentRequired.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDependentRequiredBytes() {
      java.lang.Object ref = dependentRequired_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dependentRequired_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 56000, enum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 56001, const_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(56200, multipleOf_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(56201, maximum_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(56202, exclusiveMaximum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(56203, minimum_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(56204, exclusiveMinimum_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeInt32(56400, maxLength_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeInt32(56401, minLength_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 56402, pattern_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeInt32(56600, maxItems_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeInt32(56601, minItems_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        output.writeInt32(56800, maxProperties_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        output.writeInt32(56801, maximinPropertiesmum_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 56802, required_);
      }
      if (((bitField0_ & 0x00008000) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 56803, dependentRequired_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(56000, enum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(56001, const_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56200, multipleOf_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56201, maximum_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56202, exclusiveMaximum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56203, minimum_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56204, exclusiveMinimum_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56400, maxLength_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56401, minLength_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(56402, pattern_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56600, maxItems_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56601, minItems_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56800, maxProperties_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(56801, maximinPropertiesmum_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(56802, required_);
      }
      if (((bitField0_ & 0x00008000) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(56803, dependentRequired_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary)) {
        return super.equals(obj);
      }
      vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary other = (vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary) obj;

      if (hasEnum() != other.hasEnum()) return false;
      if (hasEnum()) {
        if (!getEnum()
            .equals(other.getEnum())) return false;
      }
      if (hasConst() != other.hasConst()) return false;
      if (hasConst()) {
        if (!getConst()
            .equals(other.getConst())) return false;
      }
      if (hasMultipleOf() != other.hasMultipleOf()) return false;
      if (hasMultipleOf()) {
        if (getMultipleOf()
            != other.getMultipleOf()) return false;
      }
      if (hasMaximum() != other.hasMaximum()) return false;
      if (hasMaximum()) {
        if (getMaximum()
            != other.getMaximum()) return false;
      }
      if (hasExclusiveMaximum() != other.hasExclusiveMaximum()) return false;
      if (hasExclusiveMaximum()) {
        if (getExclusiveMaximum()
            != other.getExclusiveMaximum()) return false;
      }
      if (hasMinimum() != other.hasMinimum()) return false;
      if (hasMinimum()) {
        if (getMinimum()
            != other.getMinimum()) return false;
      }
      if (hasExclusiveMinimum() != other.hasExclusiveMinimum()) return false;
      if (hasExclusiveMinimum()) {
        if (getExclusiveMinimum()
            != other.getExclusiveMinimum()) return false;
      }
      if (hasMaxLength() != other.hasMaxLength()) return false;
      if (hasMaxLength()) {
        if (getMaxLength()
            != other.getMaxLength()) return false;
      }
      if (hasMinLength() != other.hasMinLength()) return false;
      if (hasMinLength()) {
        if (getMinLength()
            != other.getMinLength()) return false;
      }
      if (hasPattern() != other.hasPattern()) return false;
      if (hasPattern()) {
        if (!getPattern()
            .equals(other.getPattern())) return false;
      }
      if (hasMaxItems() != other.hasMaxItems()) return false;
      if (hasMaxItems()) {
        if (getMaxItems()
            != other.getMaxItems()) return false;
      }
      if (hasMinItems() != other.hasMinItems()) return false;
      if (hasMinItems()) {
        if (getMinItems()
            != other.getMinItems()) return false;
      }
      if (hasMaxProperties() != other.hasMaxProperties()) return false;
      if (hasMaxProperties()) {
        if (getMaxProperties()
            != other.getMaxProperties()) return false;
      }
      if (hasMaximinPropertiesmum() != other.hasMaximinPropertiesmum()) return false;
      if (hasMaximinPropertiesmum()) {
        if (getMaximinPropertiesmum()
            != other.getMaximinPropertiesmum()) return false;
      }
      if (hasRequired() != other.hasRequired()) return false;
      if (hasRequired()) {
        if (!getRequired()
            .equals(other.getRequired())) return false;
      }
      if (hasDependentRequired() != other.hasDependentRequired()) return false;
      if (hasDependentRequired()) {
        if (!getDependentRequired()
            .equals(other.getDependentRequired())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEnum()) {
        hash = (37 * hash) + ENUM_FIELD_NUMBER;
        hash = (53 * hash) + getEnum().hashCode();
      }
      if (hasConst()) {
        hash = (37 * hash) + CONST_FIELD_NUMBER;
        hash = (53 * hash) + getConst().hashCode();
      }
      if (hasMultipleOf()) {
        hash = (37 * hash) + MULTIPLEOF_FIELD_NUMBER;
        hash = (53 * hash) + getMultipleOf();
      }
      if (hasMaximum()) {
        hash = (37 * hash) + MAXIMUM_FIELD_NUMBER;
        hash = (53 * hash) + getMaximum();
      }
      if (hasExclusiveMaximum()) {
        hash = (37 * hash) + EXCLUSIVEMAXIMUM_FIELD_NUMBER;
        hash = (53 * hash) + getExclusiveMaximum();
      }
      if (hasMinimum()) {
        hash = (37 * hash) + MINIMUM_FIELD_NUMBER;
        hash = (53 * hash) + getMinimum();
      }
      if (hasExclusiveMinimum()) {
        hash = (37 * hash) + EXCLUSIVEMINIMUM_FIELD_NUMBER;
        hash = (53 * hash) + getExclusiveMinimum();
      }
      if (hasMaxLength()) {
        hash = (37 * hash) + MAXLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getMaxLength();
      }
      if (hasMinLength()) {
        hash = (37 * hash) + MINLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getMinLength();
      }
      if (hasPattern()) {
        hash = (37 * hash) + PATTERN_FIELD_NUMBER;
        hash = (53 * hash) + getPattern().hashCode();
      }
      if (hasMaxItems()) {
        hash = (37 * hash) + MAXITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getMaxItems();
      }
      if (hasMinItems()) {
        hash = (37 * hash) + MINITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getMinItems();
      }
      if (hasMaxProperties()) {
        hash = (37 * hash) + MAXPROPERTIES_FIELD_NUMBER;
        hash = (53 * hash) + getMaxProperties();
      }
      if (hasMaximinPropertiesmum()) {
        hash = (37 * hash) + MAXIMINPROPERTIESMUM_FIELD_NUMBER;
        hash = (53 * hash) + getMaximinPropertiesmum();
      }
      if (hasRequired()) {
        hash = (37 * hash) + REQUIRED_FIELD_NUMBER;
        hash = (53 * hash) + getRequired().hashCode();
      }
      if (hasDependentRequired()) {
        hash = (37 * hash) + DEPENDENTREQUIRED_FIELD_NUMBER;
        hash = (53 * hash) + getDependentRequired().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * *
     * Constraint Annotations Vocabulary Proto
     * (Version 1.0.0-DRAFT)
     *
     * The Constraint Annotations Vocabulary, defined as an extension of the SAS, provides commonly used metadata for 
     * annotating schemas at a physical level. Sometime is necessary to enable the consumption of data from the underlying 
     * datastore to expose these information. If this is not the case this information SHOULD not be exposed in order to hide 
     * to the consumer internal implementation details.
     *
     * Vocabulary url: 
     * - https://dpds.opendatamesh.org/specifications/sas/1.0.0-DRAFT/vocab/constraints/
     *
     * Authors: 
     * - Andrea Gioia
     *
     * LICENCE: 
     * - Apache License Version 2.0 (https://github.com/opendatamesh-initiative/odm-specification-schema-annotations/blob/main/LICENSE)
     * </pre>
     *
     * Protobuf type {@code vcb.ca.ConstraintAnnotationsVocabulary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vcb.ca.ConstraintAnnotationsVocabulary)
        vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabularyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vcb.ca.V05ConstraintVocabulary.internal_static_vcb_ca_ConstraintAnnotationsVocabulary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vcb.ca.V05ConstraintVocabulary.internal_static_vcb_ca_ConstraintAnnotationsVocabulary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.class, vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.Builder.class);
      }

      // Construct using vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        enum_ = "";
        const_ = "";
        multipleOf_ = 0;
        maximum_ = 0;
        exclusiveMaximum_ = 0;
        minimum_ = 0;
        exclusiveMinimum_ = 0;
        maxLength_ = 0;
        minLength_ = 0;
        pattern_ = "";
        maxItems_ = 0;
        minItems_ = 0;
        maxProperties_ = 0;
        maximinPropertiesmum_ = 0;
        required_ = "";
        dependentRequired_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vcb.ca.V05ConstraintVocabulary.internal_static_vcb_ca_ConstraintAnnotationsVocabulary_descriptor;
      }

      @java.lang.Override
      public vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary getDefaultInstanceForType() {
        return vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.getDefaultInstance();
      }

      @java.lang.Override
      public vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary build() {
        vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary buildPartial() {
        vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary result = new vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.enum_ = enum_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.const_ = const_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.multipleOf_ = multipleOf_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.maximum_ = maximum_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.exclusiveMaximum_ = exclusiveMaximum_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.minimum_ = minimum_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.exclusiveMinimum_ = exclusiveMinimum_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.maxLength_ = maxLength_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.minLength_ = minLength_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.pattern_ = pattern_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.maxItems_ = maxItems_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.minItems_ = minItems_;
          to_bitField0_ |= 0x00000800;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.maxProperties_ = maxProperties_;
          to_bitField0_ |= 0x00001000;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.maximinPropertiesmum_ = maximinPropertiesmum_;
          to_bitField0_ |= 0x00002000;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.required_ = required_;
          to_bitField0_ |= 0x00004000;
        }
        if (((from_bitField0_ & 0x00008000) != 0)) {
          result.dependentRequired_ = dependentRequired_;
          to_bitField0_ |= 0x00008000;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary) {
          return mergeFrom((vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary other) {
        if (other == vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.getDefaultInstance()) return this;
        if (other.hasEnum()) {
          enum_ = other.enum_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasConst()) {
          const_ = other.const_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasMultipleOf()) {
          setMultipleOf(other.getMultipleOf());
        }
        if (other.hasMaximum()) {
          setMaximum(other.getMaximum());
        }
        if (other.hasExclusiveMaximum()) {
          setExclusiveMaximum(other.getExclusiveMaximum());
        }
        if (other.hasMinimum()) {
          setMinimum(other.getMinimum());
        }
        if (other.hasExclusiveMinimum()) {
          setExclusiveMinimum(other.getExclusiveMinimum());
        }
        if (other.hasMaxLength()) {
          setMaxLength(other.getMaxLength());
        }
        if (other.hasMinLength()) {
          setMinLength(other.getMinLength());
        }
        if (other.hasPattern()) {
          pattern_ = other.pattern_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (other.hasMaxItems()) {
          setMaxItems(other.getMaxItems());
        }
        if (other.hasMinItems()) {
          setMinItems(other.getMinItems());
        }
        if (other.hasMaxProperties()) {
          setMaxProperties(other.getMaxProperties());
        }
        if (other.hasMaximinPropertiesmum()) {
          setMaximinPropertiesmum(other.getMaximinPropertiesmum());
        }
        if (other.hasRequired()) {
          required_ = other.required_;
          bitField0_ |= 0x00004000;
          onChanged();
        }
        if (other.hasDependentRequired()) {
          dependentRequired_ = other.dependentRequired_;
          bitField0_ |= 0x00008000;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 448002: {
                enum_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 448002
              case 448010: {
                const_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 448010
              case 449600: {
                multipleOf_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 449600
              case 449608: {
                maximum_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 449608
              case 449616: {
                exclusiveMaximum_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 449616
              case 449624: {
                minimum_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 449624
              case 449632: {
                exclusiveMinimum_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 449632
              case 451200: {
                maxLength_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 451200
              case 451208: {
                minLength_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 451208
              case 451218: {
                pattern_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 451218
              case 452800: {
                maxItems_ = input.readInt32();
                bitField0_ |= 0x00000400;
                break;
              } // case 452800
              case 452808: {
                minItems_ = input.readInt32();
                bitField0_ |= 0x00000800;
                break;
              } // case 452808
              case 454400: {
                maxProperties_ = input.readInt32();
                bitField0_ |= 0x00001000;
                break;
              } // case 454400
              case 454408: {
                maximinPropertiesmum_ = input.readInt32();
                bitField0_ |= 0x00002000;
                break;
              } // case 454408
              case 454418: {
                required_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00004000;
                break;
              } // case 454418
              case 454426: {
                dependentRequired_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00008000;
                break;
              } // case 454426
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object enum_ = "";
      /**
       * <pre>
       * - Keywords applicable to any properties
       * </pre>
       *
       * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the enum field is set.
       */
      public boolean hasEnum() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * - Keywords applicable to any properties
       * </pre>
       *
       * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
       * @return The enum.
       */
      public java.lang.String getEnum() {
        java.lang.Object ref = enum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          enum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * - Keywords applicable to any properties
       * </pre>
       *
       * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
       * @return The bytes for enum.
       */
      public com.google.protobuf.ByteString
          getEnumBytes() {
        java.lang.Object ref = enum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          enum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * - Keywords applicable to any properties
       * </pre>
       *
       * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The enum to set.
       * @return This builder for chaining.
       */
      public Builder setEnum(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        enum_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * - Keywords applicable to any properties
       * </pre>
       *
       * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearEnum() {
        enum_ = getDefaultInstance().getEnum();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * - Keywords applicable to any properties
       * </pre>
       *
       * <code>optional string enum = 56000 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The bytes for enum to set.
       * @return This builder for chaining.
       */
      public Builder setEnumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        enum_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object const_ = "";
      /**
       * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the const field is set.
       */
      public boolean hasConst() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
       * @return The const.
       */
      public java.lang.String getConst() {
        java.lang.Object ref = const_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          const_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
       * @return The bytes for const.
       */
      public com.google.protobuf.ByteString
          getConstBytes() {
        java.lang.Object ref = const_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          const_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The const to set.
       * @return This builder for chaining.
       */
      public Builder setConst(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        const_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearConst() {
        const_ = getDefaultInstance().getConst();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string const = 56001 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The bytes for const to set.
       * @return This builder for chaining.
       */
      public Builder setConstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        const_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int multipleOf_ ;
      /**
       * <pre>
       * - Keywords applicable to numeric properties
       * </pre>
       *
       * <code>optional int32 multipleOf = 56200 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the multipleOf field is set.
       */
      @java.lang.Override
      public boolean hasMultipleOf() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * - Keywords applicable to numeric properties
       * </pre>
       *
       * <code>optional int32 multipleOf = 56200 [targets = TARGET_TYPE_FIELD];</code>
       * @return The multipleOf.
       */
      @java.lang.Override
      public int getMultipleOf() {
        return multipleOf_;
      }
      /**
       * <pre>
       * - Keywords applicable to numeric properties
       * </pre>
       *
       * <code>optional int32 multipleOf = 56200 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The multipleOf to set.
       * @return This builder for chaining.
       */
      public Builder setMultipleOf(int value) {

        multipleOf_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * - Keywords applicable to numeric properties
       * </pre>
       *
       * <code>optional int32 multipleOf = 56200 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearMultipleOf() {
        bitField0_ = (bitField0_ & ~0x00000004);
        multipleOf_ = 0;
        onChanged();
        return this;
      }

      private int maximum_ ;
      /**
       * <code>optional int32 maximum = 56201 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the maximum field is set.
       */
      @java.lang.Override
      public boolean hasMaximum() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 maximum = 56201 [targets = TARGET_TYPE_FIELD];</code>
       * @return The maximum.
       */
      @java.lang.Override
      public int getMaximum() {
        return maximum_;
      }
      /**
       * <code>optional int32 maximum = 56201 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The maximum to set.
       * @return This builder for chaining.
       */
      public Builder setMaximum(int value) {

        maximum_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 maximum = 56201 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaximum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maximum_ = 0;
        onChanged();
        return this;
      }

      private int exclusiveMaximum_ ;
      /**
       * <code>optional int32 exclusiveMaximum = 56202 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the exclusiveMaximum field is set.
       */
      @java.lang.Override
      public boolean hasExclusiveMaximum() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 exclusiveMaximum = 56202 [targets = TARGET_TYPE_FIELD];</code>
       * @return The exclusiveMaximum.
       */
      @java.lang.Override
      public int getExclusiveMaximum() {
        return exclusiveMaximum_;
      }
      /**
       * <code>optional int32 exclusiveMaximum = 56202 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The exclusiveMaximum to set.
       * @return This builder for chaining.
       */
      public Builder setExclusiveMaximum(int value) {

        exclusiveMaximum_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exclusiveMaximum = 56202 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearExclusiveMaximum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        exclusiveMaximum_ = 0;
        onChanged();
        return this;
      }

      private int minimum_ ;
      /**
       * <code>optional int32 minimum = 56203 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the minimum field is set.
       */
      @java.lang.Override
      public boolean hasMinimum() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 minimum = 56203 [targets = TARGET_TYPE_FIELD];</code>
       * @return The minimum.
       */
      @java.lang.Override
      public int getMinimum() {
        return minimum_;
      }
      /**
       * <code>optional int32 minimum = 56203 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The minimum to set.
       * @return This builder for chaining.
       */
      public Builder setMinimum(int value) {

        minimum_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 minimum = 56203 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinimum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        minimum_ = 0;
        onChanged();
        return this;
      }

      private int exclusiveMinimum_ ;
      /**
       * <code>optional int32 exclusiveMinimum = 56204 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the exclusiveMinimum field is set.
       */
      @java.lang.Override
      public boolean hasExclusiveMinimum() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int32 exclusiveMinimum = 56204 [targets = TARGET_TYPE_FIELD];</code>
       * @return The exclusiveMinimum.
       */
      @java.lang.Override
      public int getExclusiveMinimum() {
        return exclusiveMinimum_;
      }
      /**
       * <code>optional int32 exclusiveMinimum = 56204 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The exclusiveMinimum to set.
       * @return This builder for chaining.
       */
      public Builder setExclusiveMinimum(int value) {

        exclusiveMinimum_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exclusiveMinimum = 56204 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearExclusiveMinimum() {
        bitField0_ = (bitField0_ & ~0x00000040);
        exclusiveMinimum_ = 0;
        onChanged();
        return this;
      }

      private int maxLength_ ;
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional int32 maxLength = 56400 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the maxLength field is set.
       */
      @java.lang.Override
      public boolean hasMaxLength() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional int32 maxLength = 56400 [targets = TARGET_TYPE_FIELD];</code>
       * @return The maxLength.
       */
      @java.lang.Override
      public int getMaxLength() {
        return maxLength_;
      }
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional int32 maxLength = 56400 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The maxLength to set.
       * @return This builder for chaining.
       */
      public Builder setMaxLength(int value) {

        maxLength_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional int32 maxLength = 56400 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxLength() {
        bitField0_ = (bitField0_ & ~0x00000080);
        maxLength_ = 0;
        onChanged();
        return this;
      }

      private int minLength_ ;
      /**
       * <code>optional int32 minLength = 56401 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the minLength field is set.
       */
      @java.lang.Override
      public boolean hasMinLength() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional int32 minLength = 56401 [targets = TARGET_TYPE_FIELD];</code>
       * @return The minLength.
       */
      @java.lang.Override
      public int getMinLength() {
        return minLength_;
      }
      /**
       * <code>optional int32 minLength = 56401 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The minLength to set.
       * @return This builder for chaining.
       */
      public Builder setMinLength(int value) {

        minLength_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 minLength = 56401 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinLength() {
        bitField0_ = (bitField0_ & ~0x00000100);
        minLength_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pattern_ = "";
      /**
       * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the pattern field is set.
       */
      public boolean hasPattern() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
       * @return The pattern.
       */
      public java.lang.String getPattern() {
        java.lang.Object ref = pattern_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pattern_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
       * @return The bytes for pattern.
       */
      public com.google.protobuf.ByteString
          getPatternBytes() {
        java.lang.Object ref = pattern_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pattern_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The pattern to set.
       * @return This builder for chaining.
       */
      public Builder setPattern(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        pattern_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearPattern() {
        pattern_ = getDefaultInstance().getPattern();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>optional string pattern = 56402 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The bytes for pattern to set.
       * @return This builder for chaining.
       */
      public Builder setPatternBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        pattern_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private int maxItems_ ;
      /**
       * <pre>
       * - Keywords applicable to array properties
       * </pre>
       *
       * <code>optional int32 maxItems = 56600 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the maxItems field is set.
       */
      @java.lang.Override
      public boolean hasMaxItems() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <pre>
       * - Keywords applicable to array properties
       * </pre>
       *
       * <code>optional int32 maxItems = 56600 [targets = TARGET_TYPE_FIELD];</code>
       * @return The maxItems.
       */
      @java.lang.Override
      public int getMaxItems() {
        return maxItems_;
      }
      /**
       * <pre>
       * - Keywords applicable to array properties
       * </pre>
       *
       * <code>optional int32 maxItems = 56600 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The maxItems to set.
       * @return This builder for chaining.
       */
      public Builder setMaxItems(int value) {

        maxItems_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * - Keywords applicable to array properties
       * </pre>
       *
       * <code>optional int32 maxItems = 56600 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxItems() {
        bitField0_ = (bitField0_ & ~0x00000400);
        maxItems_ = 0;
        onChanged();
        return this;
      }

      private int minItems_ ;
      /**
       * <code>optional int32 minItems = 56601 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the minItems field is set.
       */
      @java.lang.Override
      public boolean hasMinItems() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional int32 minItems = 56601 [targets = TARGET_TYPE_FIELD];</code>
       * @return The minItems.
       */
      @java.lang.Override
      public int getMinItems() {
        return minItems_;
      }
      /**
       * <code>optional int32 minItems = 56601 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The minItems to set.
       * @return This builder for chaining.
       */
      public Builder setMinItems(int value) {

        minItems_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 minItems = 56601 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearMinItems() {
        bitField0_ = (bitField0_ & ~0x00000800);
        minItems_ = 0;
        onChanged();
        return this;
      }

      private int maxProperties_ ;
      /**
       * <pre>
       * - Keywords applicable to object properties 
       * </pre>
       *
       * <code>optional int32 maxProperties = 56800 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the maxProperties field is set.
       */
      @java.lang.Override
      public boolean hasMaxProperties() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <pre>
       * - Keywords applicable to object properties 
       * </pre>
       *
       * <code>optional int32 maxProperties = 56800 [targets = TARGET_TYPE_FIELD];</code>
       * @return The maxProperties.
       */
      @java.lang.Override
      public int getMaxProperties() {
        return maxProperties_;
      }
      /**
       * <pre>
       * - Keywords applicable to object properties 
       * </pre>
       *
       * <code>optional int32 maxProperties = 56800 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The maxProperties to set.
       * @return This builder for chaining.
       */
      public Builder setMaxProperties(int value) {

        maxProperties_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * - Keywords applicable to object properties 
       * </pre>
       *
       * <code>optional int32 maxProperties = 56800 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxProperties() {
        bitField0_ = (bitField0_ & ~0x00001000);
        maxProperties_ = 0;
        onChanged();
        return this;
      }

      private int maximinPropertiesmum_ ;
      /**
       * <code>optional int32 maximinPropertiesmum = 56801 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the maximinPropertiesmum field is set.
       */
      @java.lang.Override
      public boolean hasMaximinPropertiesmum() {
        return ((bitField0_ & 0x00002000) != 0);
      }
      /**
       * <code>optional int32 maximinPropertiesmum = 56801 [targets = TARGET_TYPE_FIELD];</code>
       * @return The maximinPropertiesmum.
       */
      @java.lang.Override
      public int getMaximinPropertiesmum() {
        return maximinPropertiesmum_;
      }
      /**
       * <code>optional int32 maximinPropertiesmum = 56801 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The maximinPropertiesmum to set.
       * @return This builder for chaining.
       */
      public Builder setMaximinPropertiesmum(int value) {

        maximinPropertiesmum_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 maximinPropertiesmum = 56801 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaximinPropertiesmum() {
        bitField0_ = (bitField0_ & ~0x00002000);
        maximinPropertiesmum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object required_ = "";
      /**
       * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the required field is set.
       */
      public boolean hasRequired() {
        return ((bitField0_ & 0x00004000) != 0);
      }
      /**
       * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
       * @return The required.
       */
      public java.lang.String getRequired() {
        java.lang.Object ref = required_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          required_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
       * @return The bytes for required.
       */
      public com.google.protobuf.ByteString
          getRequiredBytes() {
        java.lang.Object ref = required_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          required_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The required to set.
       * @return This builder for chaining.
       */
      public Builder setRequired(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        required_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearRequired() {
        required_ = getDefaultInstance().getRequired();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }
      /**
       * <code>optional string required = 56802 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The bytes for required to set.
       * @return This builder for chaining.
       */
      public Builder setRequiredBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        required_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }

      private java.lang.Object dependentRequired_ = "";
      /**
       * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the dependentRequired field is set.
       */
      public boolean hasDependentRequired() {
        return ((bitField0_ & 0x00008000) != 0);
      }
      /**
       * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
       * @return The dependentRequired.
       */
      public java.lang.String getDependentRequired() {
        java.lang.Object ref = dependentRequired_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dependentRequired_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
       * @return The bytes for dependentRequired.
       */
      public com.google.protobuf.ByteString
          getDependentRequiredBytes() {
        java.lang.Object ref = dependentRequired_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dependentRequired_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The dependentRequired to set.
       * @return This builder for chaining.
       */
      public Builder setDependentRequired(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dependentRequired_ = value;
        bitField0_ |= 0x00008000;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearDependentRequired() {
        dependentRequired_ = getDefaultInstance().getDependentRequired();
        bitField0_ = (bitField0_ & ~0x00008000);
        onChanged();
        return this;
      }
      /**
       * <code>optional string dependentRequired = 56803 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The bytes for dependentRequired to set.
       * @return This builder for chaining.
       */
      public Builder setDependentRequiredBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dependentRequired_ = value;
        bitField0_ |= 0x00008000;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vcb.ca.ConstraintAnnotationsVocabulary)
    }

    // @@protoc_insertion_point(class_scope:vcb.ca.ConstraintAnnotationsVocabulary)
    private static final vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary();
    }

    public static vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConstraintAnnotationsVocabulary>
        PARSER = new com.google.protobuf.AbstractParser<ConstraintAnnotationsVocabulary>() {
      @java.lang.Override
      public ConstraintAnnotationsVocabulary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ConstraintAnnotationsVocabulary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConstraintAnnotationsVocabulary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SK_FIELD_NUMBER = 59997;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary> sk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.class,
        vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.getDefaultInstance());
  public static final int MK_FIELD_NUMBER = 59998;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary> mk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.class,
        vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.getDefaultInstance());
  public static final int FK_FIELD_NUMBER = 59999;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary> fk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.class,
        vcb.ca.V05ConstraintVocabulary.ConstraintAnnotationsVocabulary.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vcb_ca_ConstraintAnnotationsVocabulary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcb_ca_ConstraintAnnotationsVocabulary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037v05-constraint-vocabulary.proto\022\006vcb.c" +
      "a\032 google/protobuf/descriptor.proto\"\231\006\n\037" +
      "ConstraintAnnotationsVocabulary\022\030\n\004enum\030" +
      "\300\265\003 \001(\tB\003\230\001\004H\000\210\001\001\022\031\n\005const\030\301\265\003 \001(\tB\003\230\001\004H" +
      "\001\210\001\001\022\036\n\nmultipleOf\030\210\267\003 \001(\005B\003\230\001\004H\002\210\001\001\022\033\n\007" +
      "maximum\030\211\267\003 \001(\005B\003\230\001\004H\003\210\001\001\022$\n\020exclusiveMa" +
      "ximum\030\212\267\003 \001(\005B\003\230\001\004H\004\210\001\001\022\033\n\007minimum\030\213\267\003 \001" +
      "(\005B\003\230\001\004H\005\210\001\001\022$\n\020exclusiveMinimum\030\214\267\003 \001(\005" +
      "B\003\230\001\004H\006\210\001\001\022\035\n\tmaxLength\030\320\270\003 \001(\005B\003\230\001\004H\007\210\001" +
      "\001\022\035\n\tminLength\030\321\270\003 \001(\005B\003\230\001\004H\010\210\001\001\022\033\n\007patt" +
      "ern\030\322\270\003 \001(\tB\003\230\001\004H\t\210\001\001\022\034\n\010maxItems\030\230\272\003 \001(" +
      "\005B\003\230\001\004H\n\210\001\001\022\034\n\010minItems\030\231\272\003 \001(\005B\003\230\001\004H\013\210\001" +
      "\001\022!\n\rmaxProperties\030\340\273\003 \001(\005B\003\230\001\004H\014\210\001\001\022(\n\024" +
      "maximinPropertiesmum\030\341\273\003 \001(\005B\003\230\001\004H\r\210\001\001\022\034" +
      "\n\010required\030\342\273\003 \001(\tB\003\230\001\004H\016\210\001\001\022%\n\021dependen" +
      "tRequired\030\343\273\003 \001(\tB\003\230\001\004H\017\210\001\001B\007\n\005_enumB\010\n\006" +
      "_constB\r\n\013_multipleOfB\n\n\010_maximumB\023\n\021_ex" +
      "clusiveMaximumB\n\n\010_minimumB\023\n\021_exclusive" +
      "MinimumB\014\n\n_maxLengthB\014\n\n_minLengthB\n\n\010_" +
      "patternB\013\n\t_maxItemsB\013\n\t_minItemsB\020\n\016_ma" +
      "xPropertiesB\027\n\025_maximinPropertiesmumB\013\n\t" +
      "_requiredB\024\n\022_dependentRequired:S\n\002sk\022\034." +
      "google.protobuf.FileOptions\030\335\324\003 \001(\0132\'.vc" +
      "b.ca.ConstraintAnnotationsVocabulary:V\n\002" +
      "mk\022\037.google.protobuf.MessageOptions\030\336\324\003 " +
      "\001(\0132\'.vcb.ca.ConstraintAnnotationsVocabu" +
      "lary:T\n\002fk\022\035.google.protobuf.FieldOption" +
      "s\030\337\324\003 \001(\0132\'.vcb.ca.ConstraintAnnotations" +
      "Vocabularyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_vcb_ca_ConstraintAnnotationsVocabulary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vcb_ca_ConstraintAnnotationsVocabulary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vcb_ca_ConstraintAnnotationsVocabulary_descriptor,
        new java.lang.String[] { "Enum", "Const", "MultipleOf", "Maximum", "ExclusiveMaximum", "Minimum", "ExclusiveMinimum", "MaxLength", "MinLength", "Pattern", "MaxItems", "MinItems", "MaxProperties", "MaximinPropertiesmum", "Required", "DependentRequired", });
    sk.internalInit(descriptor.getExtensions().get(0));
    mk.internalInit(descriptor.getExtensions().get(1));
    fk.internalInit(descriptor.getExtensions().get(2));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
