// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v02-meta-data-basic-vocabulary.proto
// Protobuf Java Version: 4.29.3

package vcb.mdb;

public final class V02MetaDataBasicVocabulary {
  private V02MetaDataBasicVocabulary() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      V02MetaDataBasicVocabulary.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(vcb.mdb.V02MetaDataBasicVocabulary.sk);
    registry.add(vcb.mdb.V02MetaDataBasicVocabulary.mk);
    registry.add(vcb.mdb.V02MetaDataBasicVocabulary.fk);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MetadataVocabularyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vcb.mdb.MetadataVocabulary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Keywords applicable to schema or properties
     * </pre>
     *
     * <code>optional string title = 20001;</code>
     * @return Whether the title field is set.
     */
    boolean hasTitle();
    /**
     * <pre>
     * Keywords applicable to schema or properties
     * </pre>
     *
     * <code>optional string title = 20001;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <pre>
     * Keywords applicable to schema or properties
     * </pre>
     *
     * <code>optional string title = 20001;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string description = 20002;</code>
     * @return Whether the description field is set.
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 20002;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 20002;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional string default = 20003;</code>
     * @return Whether the default field is set.
     */
    boolean hasDefault();
    /**
     * <code>optional string default = 20003;</code>
     * @return The default.
     */
    java.lang.String getDefault();
    /**
     * <code>optional string default = 20003;</code>
     * @return The bytes for default.
     */
    com.google.protobuf.ByteString
        getDefaultBytes();

    /**
     * <code>optional bool deprecated = 20004;</code>
     * @return Whether the deprecated field is set.
     */
    boolean hasDeprecated();
    /**
     * <code>optional bool deprecated = 20004;</code>
     * @return The deprecated.
     */
    boolean getDeprecated();

    /**
     * <pre>
     * Keywords applicable only to properties
     * </pre>
     *
     * <code>optional bool writeOnly = 25001 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the writeOnly field is set.
     */
    boolean hasWriteOnly();
    /**
     * <pre>
     * Keywords applicable only to properties
     * </pre>
     *
     * <code>optional bool writeOnly = 25001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The writeOnly.
     */
    boolean getWriteOnly();

    /**
     * <code>optional bool readOnly = 25002 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the readOnly field is set.
     */
    boolean hasReadOnly();
    /**
     * <code>optional bool readOnly = 25002 [targets = TARGET_TYPE_FIELD];</code>
     * @return The readOnly.
     */
    boolean getReadOnly();
  }
  /**
   * <pre>
   * *
   * Basic Meta-Data Annotations Vocabulary Proto
   * (Version 1.0.0-DRAFT)
   *
   * These general-purpose annotation vocabulary defided in JSON Schema Validation extension provide commonly used information 
   * for documentation and user interface display purposes. They are not intended to form a comprehensive set of features. 
   * Rather, additional vocabularies can be defined for more complex annotation-based applications.
   *
   * Vocabulary url: 
   * - https://json-schema.org/draft/2020-12/meta/meta-data
   *
   * Authors: 
   * - Andrea Gioia
   *
   * LICENCE: 
   * - Apache License Version 2.0 (https://github.com/opendatamesh-initiative/odm-specification-schema-annotations/blob/main/LICENSE)
   * </pre>
   *
   * Protobuf type {@code vcb.mdb.MetadataVocabulary}
   */
  public static final class MetadataVocabulary extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vcb.mdb.MetadataVocabulary)
      MetadataVocabularyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MetadataVocabulary.class.getName());
    }
    // Use MetadataVocabulary.newBuilder() to construct.
    private MetadataVocabulary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MetadataVocabulary() {
      title_ = "";
      description_ = "";
      default_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vcb.mdb.V02MetaDataBasicVocabulary.internal_static_vcb_mdb_MetadataVocabulary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vcb.mdb.V02MetaDataBasicVocabulary.internal_static_vcb_mdb_MetadataVocabulary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.class, vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 20001;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <pre>
     * Keywords applicable to schema or properties
     * </pre>
     *
     * <code>optional string title = 20001;</code>
     * @return Whether the title field is set.
     */
    @java.lang.Override
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Keywords applicable to schema or properties
     * </pre>
     *
     * <code>optional string title = 20001;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Keywords applicable to schema or properties
     * </pre>
     *
     * <code>optional string title = 20001;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 20002;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>optional string description = 20002;</code>
     * @return Whether the description field is set.
     */
    @java.lang.Override
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string description = 20002;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>optional string description = 20002;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEFAULT_FIELD_NUMBER = 20003;
    @SuppressWarnings("serial")
    private volatile java.lang.Object default_ = "";
    /**
     * <code>optional string default = 20003;</code>
     * @return Whether the default field is set.
     */
    @java.lang.Override
    public boolean hasDefault() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string default = 20003;</code>
     * @return The default.
     */
    @java.lang.Override
    public java.lang.String getDefault() {
      java.lang.Object ref = default_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        default_ = s;
        return s;
      }
    }
    /**
     * <code>optional string default = 20003;</code>
     * @return The bytes for default.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDefaultBytes() {
      java.lang.Object ref = default_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        default_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPRECATED_FIELD_NUMBER = 20004;
    private boolean deprecated_ = false;
    /**
     * <code>optional bool deprecated = 20004;</code>
     * @return Whether the deprecated field is set.
     */
    @java.lang.Override
    public boolean hasDeprecated() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool deprecated = 20004;</code>
     * @return The deprecated.
     */
    @java.lang.Override
    public boolean getDeprecated() {
      return deprecated_;
    }

    public static final int WRITEONLY_FIELD_NUMBER = 25001;
    private boolean writeOnly_ = false;
    /**
     * <pre>
     * Keywords applicable only to properties
     * </pre>
     *
     * <code>optional bool writeOnly = 25001 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the writeOnly field is set.
     */
    @java.lang.Override
    public boolean hasWriteOnly() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Keywords applicable only to properties
     * </pre>
     *
     * <code>optional bool writeOnly = 25001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The writeOnly.
     */
    @java.lang.Override
    public boolean getWriteOnly() {
      return writeOnly_;
    }

    public static final int READONLY_FIELD_NUMBER = 25002;
    private boolean readOnly_ = false;
    /**
     * <code>optional bool readOnly = 25002 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the readOnly field is set.
     */
    @java.lang.Override
    public boolean hasReadOnly() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool readOnly = 25002 [targets = TARGET_TYPE_FIELD];</code>
     * @return The readOnly.
     */
    @java.lang.Override
    public boolean getReadOnly() {
      return readOnly_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 20001, title_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 20002, description_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 20003, default_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(20004, deprecated_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(25001, writeOnly_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(25002, readOnly_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(20001, title_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(20002, description_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(20003, default_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(20004, deprecated_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(25001, writeOnly_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(25002, readOnly_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary)) {
        return super.equals(obj);
      }
      vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary other = (vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary) obj;

      if (hasTitle() != other.hasTitle()) return false;
      if (hasTitle()) {
        if (!getTitle()
            .equals(other.getTitle())) return false;
      }
      if (hasDescription() != other.hasDescription()) return false;
      if (hasDescription()) {
        if (!getDescription()
            .equals(other.getDescription())) return false;
      }
      if (hasDefault() != other.hasDefault()) return false;
      if (hasDefault()) {
        if (!getDefault()
            .equals(other.getDefault())) return false;
      }
      if (hasDeprecated() != other.hasDeprecated()) return false;
      if (hasDeprecated()) {
        if (getDeprecated()
            != other.getDeprecated()) return false;
      }
      if (hasWriteOnly() != other.hasWriteOnly()) return false;
      if (hasWriteOnly()) {
        if (getWriteOnly()
            != other.getWriteOnly()) return false;
      }
      if (hasReadOnly() != other.hasReadOnly()) return false;
      if (hasReadOnly()) {
        if (getReadOnly()
            != other.getReadOnly()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasDescription()) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
      }
      if (hasDefault()) {
        hash = (37 * hash) + DEFAULT_FIELD_NUMBER;
        hash = (53 * hash) + getDefault().hashCode();
      }
      if (hasDeprecated()) {
        hash = (37 * hash) + DEPRECATED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDeprecated());
      }
      if (hasWriteOnly()) {
        hash = (37 * hash) + WRITEONLY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getWriteOnly());
      }
      if (hasReadOnly()) {
        hash = (37 * hash) + READONLY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getReadOnly());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * *
     * Basic Meta-Data Annotations Vocabulary Proto
     * (Version 1.0.0-DRAFT)
     *
     * These general-purpose annotation vocabulary defided in JSON Schema Validation extension provide commonly used information 
     * for documentation and user interface display purposes. They are not intended to form a comprehensive set of features. 
     * Rather, additional vocabularies can be defined for more complex annotation-based applications.
     *
     * Vocabulary url: 
     * - https://json-schema.org/draft/2020-12/meta/meta-data
     *
     * Authors: 
     * - Andrea Gioia
     *
     * LICENCE: 
     * - Apache License Version 2.0 (https://github.com/opendatamesh-initiative/odm-specification-schema-annotations/blob/main/LICENSE)
     * </pre>
     *
     * Protobuf type {@code vcb.mdb.MetadataVocabulary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vcb.mdb.MetadataVocabulary)
        vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabularyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vcb.mdb.V02MetaDataBasicVocabulary.internal_static_vcb_mdb_MetadataVocabulary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vcb.mdb.V02MetaDataBasicVocabulary.internal_static_vcb_mdb_MetadataVocabulary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.class, vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.Builder.class);
      }

      // Construct using vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        title_ = "";
        description_ = "";
        default_ = "";
        deprecated_ = false;
        writeOnly_ = false;
        readOnly_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vcb.mdb.V02MetaDataBasicVocabulary.internal_static_vcb_mdb_MetadataVocabulary_descriptor;
      }

      @java.lang.Override
      public vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary getDefaultInstanceForType() {
        return vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.getDefaultInstance();
      }

      @java.lang.Override
      public vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary build() {
        vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary buildPartial() {
        vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary result = new vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.title_ = title_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.description_ = description_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.default_ = default_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.deprecated_ = deprecated_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.writeOnly_ = writeOnly_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.readOnly_ = readOnly_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary) {
          return mergeFrom((vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary other) {
        if (other == vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          title_ = other.title_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasDescription()) {
          description_ = other.description_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasDefault()) {
          default_ = other.default_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasDeprecated()) {
          setDeprecated(other.getDeprecated());
        }
        if (other.hasWriteOnly()) {
          setWriteOnly(other.getWriteOnly());
        }
        if (other.hasReadOnly()) {
          setReadOnly(other.getReadOnly());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 160010: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 160010
              case 160018: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 160018
              case 160026: {
                default_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 160026
              case 160032: {
                deprecated_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 160032
              case 200008: {
                writeOnly_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 200008
              case 200016: {
                readOnly_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 200016
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <pre>
       * Keywords applicable to schema or properties
       * </pre>
       *
       * <code>optional string title = 20001;</code>
       * @return Whether the title field is set.
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Keywords applicable to schema or properties
       * </pre>
       *
       * <code>optional string title = 20001;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Keywords applicable to schema or properties
       * </pre>
       *
       * <code>optional string title = 20001;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Keywords applicable to schema or properties
       * </pre>
       *
       * <code>optional string title = 20001;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Keywords applicable to schema or properties
       * </pre>
       *
       * <code>optional string title = 20001;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Keywords applicable to schema or properties
       * </pre>
       *
       * <code>optional string title = 20001;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 20002;</code>
       * @return Whether the description field is set.
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string description = 20002;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 20002;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 20002;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 20002;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 20002;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object default_ = "";
      /**
       * <code>optional string default = 20003;</code>
       * @return Whether the default field is set.
       */
      public boolean hasDefault() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string default = 20003;</code>
       * @return The default.
       */
      public java.lang.String getDefault() {
        java.lang.Object ref = default_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          default_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string default = 20003;</code>
       * @return The bytes for default.
       */
      public com.google.protobuf.ByteString
          getDefaultBytes() {
        java.lang.Object ref = default_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          default_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string default = 20003;</code>
       * @param value The default to set.
       * @return This builder for chaining.
       */
      public Builder setDefault(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        default_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string default = 20003;</code>
       * @return This builder for chaining.
       */
      public Builder clearDefault() {
        default_ = getDefaultInstance().getDefault();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string default = 20003;</code>
       * @param value The bytes for default to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        default_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private boolean deprecated_ ;
      /**
       * <code>optional bool deprecated = 20004;</code>
       * @return Whether the deprecated field is set.
       */
      @java.lang.Override
      public boolean hasDeprecated() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bool deprecated = 20004;</code>
       * @return The deprecated.
       */
      @java.lang.Override
      public boolean getDeprecated() {
        return deprecated_;
      }
      /**
       * <code>optional bool deprecated = 20004;</code>
       * @param value The deprecated to set.
       * @return This builder for chaining.
       */
      public Builder setDeprecated(boolean value) {

        deprecated_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool deprecated = 20004;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeprecated() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deprecated_ = false;
        onChanged();
        return this;
      }

      private boolean writeOnly_ ;
      /**
       * <pre>
       * Keywords applicable only to properties
       * </pre>
       *
       * <code>optional bool writeOnly = 25001 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the writeOnly field is set.
       */
      @java.lang.Override
      public boolean hasWriteOnly() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * Keywords applicable only to properties
       * </pre>
       *
       * <code>optional bool writeOnly = 25001 [targets = TARGET_TYPE_FIELD];</code>
       * @return The writeOnly.
       */
      @java.lang.Override
      public boolean getWriteOnly() {
        return writeOnly_;
      }
      /**
       * <pre>
       * Keywords applicable only to properties
       * </pre>
       *
       * <code>optional bool writeOnly = 25001 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The writeOnly to set.
       * @return This builder for chaining.
       */
      public Builder setWriteOnly(boolean value) {

        writeOnly_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Keywords applicable only to properties
       * </pre>
       *
       * <code>optional bool writeOnly = 25001 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearWriteOnly() {
        bitField0_ = (bitField0_ & ~0x00000010);
        writeOnly_ = false;
        onChanged();
        return this;
      }

      private boolean readOnly_ ;
      /**
       * <code>optional bool readOnly = 25002 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the readOnly field is set.
       */
      @java.lang.Override
      public boolean hasReadOnly() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bool readOnly = 25002 [targets = TARGET_TYPE_FIELD];</code>
       * @return The readOnly.
       */
      @java.lang.Override
      public boolean getReadOnly() {
        return readOnly_;
      }
      /**
       * <code>optional bool readOnly = 25002 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The readOnly to set.
       * @return This builder for chaining.
       */
      public Builder setReadOnly(boolean value) {

        readOnly_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool readOnly = 25002 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearReadOnly() {
        bitField0_ = (bitField0_ & ~0x00000020);
        readOnly_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vcb.mdb.MetadataVocabulary)
    }

    // @@protoc_insertion_point(class_scope:vcb.mdb.MetadataVocabulary)
    private static final vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary();
    }

    public static vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MetadataVocabulary>
        PARSER = new com.google.protobuf.AbstractParser<MetadataVocabulary>() {
      @java.lang.Override
      public MetadataVocabulary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MetadataVocabulary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MetadataVocabulary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SK_FIELD_NUMBER = 29997;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary> sk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.class,
        vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.getDefaultInstance());
  public static final int MK_FIELD_NUMBER = 29998;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary> mk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.class,
        vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.getDefaultInstance());
  public static final int FK_FIELD_NUMBER = 29999;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary> fk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.class,
        vcb.mdb.V02MetaDataBasicVocabulary.MetadataVocabulary.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vcb_mdb_MetadataVocabulary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcb_mdb_MetadataVocabulary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$v02-meta-data-basic-vocabulary.proto\022\007" +
      "vcb.mdb\032 google/protobuf/descriptor.prot" +
      "o\"\206\002\n\022MetadataVocabulary\022\024\n\005title\030\241\234\001 \001(" +
      "\tH\000\210\001\001\022\032\n\013description\030\242\234\001 \001(\tH\001\210\001\001\022\026\n\007de" +
      "fault\030\243\234\001 \001(\tH\002\210\001\001\022\031\n\ndeprecated\030\244\234\001 \001(\010" +
      "H\003\210\001\001\022\035\n\twriteOnly\030\251\303\001 \001(\010B\003\230\001\004H\004\210\001\001\022\034\n\010" +
      "readOnly\030\252\303\001 \001(\010B\003\230\001\004H\005\210\001\001B\010\n\006_titleB\016\n\014" +
      "_descriptionB\n\n\010_defaultB\r\n\013_deprecatedB" +
      "\014\n\n_writeOnlyB\013\n\t_readOnly:G\n\002sk\022\034.googl" +
      "e.protobuf.FileOptions\030\255\352\001 \001(\0132\033.vcb.mdb" +
      ".MetadataVocabulary:J\n\002mk\022\037.google.proto" +
      "buf.MessageOptions\030\256\352\001 \001(\0132\033.vcb.mdb.Met" +
      "adataVocabulary:H\n\002fk\022\035.google.protobuf." +
      "FieldOptions\030\257\352\001 \001(\0132\033.vcb.mdb.MetadataV" +
      "ocabularyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_vcb_mdb_MetadataVocabulary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vcb_mdb_MetadataVocabulary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vcb_mdb_MetadataVocabulary_descriptor,
        new java.lang.String[] { "Title", "Description", "Default", "Deprecated", "WriteOnly", "ReadOnly", });
    sk.internalInit(descriptor.getExtensions().get(0));
    mk.internalInit(descriptor.getExtensions().get(1));
    fk.internalInit(descriptor.getExtensions().get(2));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
