// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: emlpoyee.proto
// Protobuf Java Version: 4.29.3

package it.quantyca.protobuf;

public final class EmployeeProtos {
  private EmployeeProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      EmployeeProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(it.quantyca.protobuf.EmployeeProtos.testFileKeyword);
    registry.add(it.quantyca.protobuf.EmployeeProtos.messageFileKeyword);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.quantyca.protobuf.Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Identifier
     * </pre>
     *
     * <code>int32 id = 1 [(.vcb.mdb.fk) = { ... }</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * Name
     * </pre>
     *
     * <code>string name = 2 [(.vcb.mdb.fk) = { ... }</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * Name
     * </pre>
     *
     * <code>string name = 2 [(.vcb.mdb.fk) = { ... }</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Department
     * </pre>
     *
     * <code>string department = 3 [(.vcb.mdb.fk) = { ... }</code>
     * @return The department.
     */
    java.lang.String getDepartment();
    /**
     * <pre>
     * Department
     * </pre>
     *
     * <code>string department = 3 [(.vcb.mdb.fk) = { ... }</code>
     * @return The bytes for department.
     */
    com.google.protobuf.ByteString
        getDepartmentBytes();

    /**
     * <pre>
     * Salary
     * </pre>
     *
     * <code>double salary = 4 [(.vcb.mdb.fk) = { ... }</code>
     * @return The salary.
     */
    double getSalary();
  }
  /**
   * <pre>
   * Employee's data
   * </pre>
   *
   * Protobuf type {@code it.quantyca.protobuf.Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:it.quantyca.protobuf.Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Employee.class.getName());
    }
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      name_ = "";
      department_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.quantyca.protobuf.EmployeeProtos.internal_static_it_quantyca_protobuf_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.quantyca.protobuf.EmployeeProtos.internal_static_it_quantyca_protobuf_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.quantyca.protobuf.EmployeeProtos.Employee.class, it.quantyca.protobuf.EmployeeProtos.Employee.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <pre>
     * Identifier
     * </pre>
     *
     * <code>int32 id = 1 [(.vcb.mdb.fk) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * Name
     * </pre>
     *
     * <code>string name = 2 [(.vcb.mdb.fk) = { ... }</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Name
     * </pre>
     *
     * <code>string name = 2 [(.vcb.mdb.fk) = { ... }</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPARTMENT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object department_ = "";
    /**
     * <pre>
     * Department
     * </pre>
     *
     * <code>string department = 3 [(.vcb.mdb.fk) = { ... }</code>
     * @return The department.
     */
    @java.lang.Override
    public java.lang.String getDepartment() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        department_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Department
     * </pre>
     *
     * <code>string department = 3 [(.vcb.mdb.fk) = { ... }</code>
     * @return The bytes for department.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDepartmentBytes() {
      java.lang.Object ref = department_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        department_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALARY_FIELD_NUMBER = 4;
    private double salary_ = 0D;
    /**
     * <pre>
     * Salary
     * </pre>
     *
     * <code>double salary = 4 [(.vcb.mdb.fk) = { ... }</code>
     * @return The salary.
     */
    @java.lang.Override
    public double getSalary() {
      return salary_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(department_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, department_);
      }
      if (java.lang.Double.doubleToRawLongBits(salary_) != 0) {
        output.writeDouble(4, salary_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(department_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, department_);
      }
      if (java.lang.Double.doubleToRawLongBits(salary_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, salary_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.quantyca.protobuf.EmployeeProtos.Employee)) {
        return super.equals(obj);
      }
      it.quantyca.protobuf.EmployeeProtos.Employee other = (it.quantyca.protobuf.EmployeeProtos.Employee) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDepartment()
          .equals(other.getDepartment())) return false;
      if (java.lang.Double.doubleToLongBits(getSalary())
          != java.lang.Double.doubleToLongBits(
              other.getSalary())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDepartment().hashCode();
      hash = (37 * hash) + SALARY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSalary()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static it.quantyca.protobuf.EmployeeProtos.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static it.quantyca.protobuf.EmployeeProtos.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static it.quantyca.protobuf.EmployeeProtos.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.quantyca.protobuf.EmployeeProtos.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Employee's data
     * </pre>
     *
     * Protobuf type {@code it.quantyca.protobuf.Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.quantyca.protobuf.Employee)
        it.quantyca.protobuf.EmployeeProtos.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.quantyca.protobuf.EmployeeProtos.internal_static_it_quantyca_protobuf_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.quantyca.protobuf.EmployeeProtos.internal_static_it_quantyca_protobuf_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.quantyca.protobuf.EmployeeProtos.Employee.class, it.quantyca.protobuf.EmployeeProtos.Employee.Builder.class);
      }

      // Construct using it.quantyca.protobuf.EmployeeProtos.Employee.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        department_ = "";
        salary_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.quantyca.protobuf.EmployeeProtos.internal_static_it_quantyca_protobuf_Employee_descriptor;
      }

      @java.lang.Override
      public it.quantyca.protobuf.EmployeeProtos.Employee getDefaultInstanceForType() {
        return it.quantyca.protobuf.EmployeeProtos.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public it.quantyca.protobuf.EmployeeProtos.Employee build() {
        it.quantyca.protobuf.EmployeeProtos.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.quantyca.protobuf.EmployeeProtos.Employee buildPartial() {
        it.quantyca.protobuf.EmployeeProtos.Employee result = new it.quantyca.protobuf.EmployeeProtos.Employee(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(it.quantyca.protobuf.EmployeeProtos.Employee result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.department_ = department_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.salary_ = salary_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.quantyca.protobuf.EmployeeProtos.Employee) {
          return mergeFrom((it.quantyca.protobuf.EmployeeProtos.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.quantyca.protobuf.EmployeeProtos.Employee other) {
        if (other == it.quantyca.protobuf.EmployeeProtos.Employee.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDepartment().isEmpty()) {
          department_ = other.department_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getSalary() != 0D) {
          setSalary(other.getSalary());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                department_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 33: {
                salary_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * Identifier
       * </pre>
       *
       * <code>int32 id = 1 [(.vcb.mdb.fk) = { ... }</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * Identifier
       * </pre>
       *
       * <code>int32 id = 1 [(.vcb.mdb.fk) = { ... }</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Identifier
       * </pre>
       *
       * <code>int32 id = 1 [(.vcb.mdb.fk) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Name
       * </pre>
       *
       * <code>string name = 2 [(.vcb.mdb.fk) = { ... }</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Name
       * </pre>
       *
       * <code>string name = 2 [(.vcb.mdb.fk) = { ... }</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Name
       * </pre>
       *
       * <code>string name = 2 [(.vcb.mdb.fk) = { ... }</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name
       * </pre>
       *
       * <code>string name = 2 [(.vcb.mdb.fk) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Name
       * </pre>
       *
       * <code>string name = 2 [(.vcb.mdb.fk) = { ... }</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object department_ = "";
      /**
       * <pre>
       * Department
       * </pre>
       *
       * <code>string department = 3 [(.vcb.mdb.fk) = { ... }</code>
       * @return The department.
       */
      public java.lang.String getDepartment() {
        java.lang.Object ref = department_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          department_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Department
       * </pre>
       *
       * <code>string department = 3 [(.vcb.mdb.fk) = { ... }</code>
       * @return The bytes for department.
       */
      public com.google.protobuf.ByteString
          getDepartmentBytes() {
        java.lang.Object ref = department_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          department_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Department
       * </pre>
       *
       * <code>string department = 3 [(.vcb.mdb.fk) = { ... }</code>
       * @param value The department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartment(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        department_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Department
       * </pre>
       *
       * <code>string department = 3 [(.vcb.mdb.fk) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearDepartment() {
        department_ = getDefaultInstance().getDepartment();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Department
       * </pre>
       *
       * <code>string department = 3 [(.vcb.mdb.fk) = { ... }</code>
       * @param value The bytes for department to set.
       * @return This builder for chaining.
       */
      public Builder setDepartmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        department_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private double salary_ ;
      /**
       * <pre>
       * Salary
       * </pre>
       *
       * <code>double salary = 4 [(.vcb.mdb.fk) = { ... }</code>
       * @return The salary.
       */
      @java.lang.Override
      public double getSalary() {
        return salary_;
      }
      /**
       * <pre>
       * Salary
       * </pre>
       *
       * <code>double salary = 4 [(.vcb.mdb.fk) = { ... }</code>
       * @param value The salary to set.
       * @return This builder for chaining.
       */
      public Builder setSalary(double value) {

        salary_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Salary
       * </pre>
       *
       * <code>double salary = 4 [(.vcb.mdb.fk) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearSalary() {
        bitField0_ = (bitField0_ & ~0x00000008);
        salary_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:it.quantyca.protobuf.Employee)
    }

    // @@protoc_insertion_point(class_scope:it.quantyca.protobuf.Employee)
    private static final it.quantyca.protobuf.EmployeeProtos.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.quantyca.protobuf.EmployeeProtos.Employee();
    }

    public static it.quantyca.protobuf.EmployeeProtos.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.quantyca.protobuf.EmployeeProtos.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TESTFILEKEYWORD_FIELD_NUMBER = 136001;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.lang.String> testFileKeyword = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int MESSAGEFILEKEYWORD_FIELD_NUMBER = 136002;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> messageFileKeyword = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_quantyca_protobuf_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_it_quantyca_protobuf_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016emlpoyee.proto\022\024it.quantyca.protobuf\032 " +
      "google/protobuf/descriptor.proto\032$v02-me" +
      "ta-data-basic-vocabulary.proto\032&v03-meta" +
      "-data-logical-vocabulary.proto\"\235\002\n\010Emplo" +
      "yee\022&\n\002id\030\001 \001(\005B\032\372\322\016\016\212\342\t\nIdentifier\372\303\023\004\230" +
      "\312\021\001\022\032\n\004name\030\002 \001(\tB\014\372\322\016\010\212\342\t\004Name\022&\n\ndepar" +
      "tment\030\003 \001(\tB\022\372\322\016\016\212\342\t\nDepartment\022\036\n\006salar" +
      "y\030\004 \001(\001B\016\372\322\016\n\212\342\t\006Salary:\204\001\362\322\016\023\212\342\t\017Employ" +
      "ee\'s data\342\312\021 vcb.mdl.testMessageKeyword " +
      "value\362\303\023)\212\323\016\033Key data about the employee" +
      "\302\216\020\006Andrea\222\264B\030messageFileKeyword value::" +
      "\n\017testFileKeyword\022\034.google.protobuf.File" +
      "Options\030\301\246\010 \001(\t\210\001\001:@\n\022messageFileKeyword" +
      "\022\037.google.protobuf.MessageOptions\030\302\246\010 \001(" +
      "\t\210\001\001B>B\016EmployeeProtos\352\303\023\021\212\323\016\rEmploy pro" +
      "tos\212\264B\025testFileKeyword valueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          vcb.mdb.V02MetaDataBasicVocabulary.getDescriptor(),
          vcb.mdl.V03MetaDataLogicalVocabulary.getDescriptor(),
        });
    internal_static_it_quantyca_protobuf_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_it_quantyca_protobuf_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_it_quantyca_protobuf_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", "Department", "Salary", });
    testFileKeyword.internalInit(descriptor.getExtensions().get(0));
    messageFileKeyword.internalInit(descriptor.getExtensions().get(1));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
    vcb.mdb.V02MetaDataBasicVocabulary.getDescriptor();
    vcb.mdl.V03MetaDataLogicalVocabulary.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(it.quantyca.protobuf.EmployeeProtos.messageFileKeyword);
    registry.add(it.quantyca.protobuf.EmployeeProtos.testFileKeyword);
    registry.add(vcb.mdb.V02MetaDataBasicVocabulary.fk);
    registry.add(vcb.mdb.V02MetaDataBasicVocabulary.mk);
    registry.add(vcb.mdl.V03MetaDataLogicalVocabulary.fk);
    registry.add(vcb.mdl.V03MetaDataLogicalVocabulary.mk);
    registry.add(vcb.mdl.V03MetaDataLogicalVocabulary.sk);
    registry.add(vcb.mdl.V03MetaDataLogicalVocabulary.testMessageKeyword);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
