// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v06-content-vocabulary.proto
// Protobuf Java Version: 4.29.3

package vcb.sec;

public final class V06ContentVocabulary {
  private V06ContentVocabulary() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      V06ContentVocabulary.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(vcb.sec.V06ContentVocabulary.sk);
    registry.add(vcb.sec.V06ContentVocabulary.mk);
    registry.add(vcb.sec.V06ContentVocabulary.fk);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContentVocabularyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vcb.sec.ContentVocabulary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the contentEncoding field is set.
     */
    boolean hasContentEncoding();
    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The contentEncoding.
     */
    java.lang.String getContentEncoding();
    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for contentEncoding.
     */
    com.google.protobuf.ByteString
        getContentEncodingBytes();

    /**
     * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the contentMediaType field is set.
     */
    boolean hasContentMediaType();
    /**
     * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The contentMediaType.
     */
    java.lang.String getContentMediaType();
    /**
     * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for contentMediaType.
     */
    com.google.protobuf.ByteString
        getContentMediaTypeBytes();

    /**
     * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the contentSchema field is set.
     */
    boolean hasContentSchema();
    /**
     * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
     * @return The contentSchema.
     */
    java.lang.String getContentSchema();
    /**
     * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for contentSchema.
     */
    com.google.protobuf.ByteString
        getContentSchemaBytes();
  }
  /**
   * <pre>
   * *
   * String-encoded Content Vocabulary Proto
   * (Version 1.0.0-DRAFT)
   *
   * This vocabulary defided in JSON Schema Validation extension describe the format keyword defined to allow schema authors 
   * to convey syntactic information for a fixed subset of values which are accurately described by authoritative resources, be 
   * they RFCs or other external specifications
   *
   * Vocabulary url: 
   * -https://json-schema.org/draft/2020-12/meta/format-annotation
   *
   * Authors: 
   * - Andrea Gioia
   *
   * LICENCE: 
   * - Apache License Version 2.0 (https://github.com/opendatamesh-initiative/odm-specification-schema-annotations/blob/main/LICENSE)
   * </pre>
   *
   * Protobuf type {@code vcb.sec.ContentVocabulary}
   */
  public static final class ContentVocabulary extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vcb.sec.ContentVocabulary)
      ContentVocabularyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ContentVocabulary.class.getName());
    }
    // Use ContentVocabulary.newBuilder() to construct.
    private ContentVocabulary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ContentVocabulary() {
      contentEncoding_ = "";
      contentMediaType_ = "";
      contentSchema_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vcb.sec.V06ContentVocabulary.internal_static_vcb_sec_ContentVocabulary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vcb.sec.V06ContentVocabulary.internal_static_vcb_sec_ContentVocabulary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vcb.sec.V06ContentVocabulary.ContentVocabulary.class, vcb.sec.V06ContentVocabulary.ContentVocabulary.Builder.class);
    }

    private int bitField0_;
    public static final int CONTENTENCODING_FIELD_NUMBER = 62000;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contentEncoding_ = "";
    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the contentEncoding field is set.
     */
    @java.lang.Override
    public boolean hasContentEncoding() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The contentEncoding.
     */
    @java.lang.Override
    public java.lang.String getContentEncoding() {
      java.lang.Object ref = contentEncoding_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentEncoding_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * - Keywords applicable to string properties
     * </pre>
     *
     * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for contentEncoding.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentEncodingBytes() {
      java.lang.Object ref = contentEncoding_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentEncoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTMEDIATYPE_FIELD_NUMBER = 62001;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contentMediaType_ = "";
    /**
     * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the contentMediaType field is set.
     */
    @java.lang.Override
    public boolean hasContentMediaType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The contentMediaType.
     */
    @java.lang.Override
    public java.lang.String getContentMediaType() {
      java.lang.Object ref = contentMediaType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentMediaType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for contentMediaType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentMediaTypeBytes() {
      java.lang.Object ref = contentMediaType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentMediaType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTSCHEMA_FIELD_NUMBER = 62002;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contentSchema_ = "";
    /**
     * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the contentSchema field is set.
     */
    @java.lang.Override
    public boolean hasContentSchema() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
     * @return The contentSchema.
     */
    @java.lang.Override
    public java.lang.String getContentSchema() {
      java.lang.Object ref = contentSchema_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentSchema_ = s;
        return s;
      }
    }
    /**
     * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for contentSchema.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentSchemaBytes() {
      java.lang.Object ref = contentSchema_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentSchema_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 62000, contentEncoding_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 62001, contentMediaType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 62002, contentSchema_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(62000, contentEncoding_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(62001, contentMediaType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(62002, contentSchema_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vcb.sec.V06ContentVocabulary.ContentVocabulary)) {
        return super.equals(obj);
      }
      vcb.sec.V06ContentVocabulary.ContentVocabulary other = (vcb.sec.V06ContentVocabulary.ContentVocabulary) obj;

      if (hasContentEncoding() != other.hasContentEncoding()) return false;
      if (hasContentEncoding()) {
        if (!getContentEncoding()
            .equals(other.getContentEncoding())) return false;
      }
      if (hasContentMediaType() != other.hasContentMediaType()) return false;
      if (hasContentMediaType()) {
        if (!getContentMediaType()
            .equals(other.getContentMediaType())) return false;
      }
      if (hasContentSchema() != other.hasContentSchema()) return false;
      if (hasContentSchema()) {
        if (!getContentSchema()
            .equals(other.getContentSchema())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasContentEncoding()) {
        hash = (37 * hash) + CONTENTENCODING_FIELD_NUMBER;
        hash = (53 * hash) + getContentEncoding().hashCode();
      }
      if (hasContentMediaType()) {
        hash = (37 * hash) + CONTENTMEDIATYPE_FIELD_NUMBER;
        hash = (53 * hash) + getContentMediaType().hashCode();
      }
      if (hasContentSchema()) {
        hash = (37 * hash) + CONTENTSCHEMA_FIELD_NUMBER;
        hash = (53 * hash) + getContentSchema().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.sec.V06ContentVocabulary.ContentVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vcb.sec.V06ContentVocabulary.ContentVocabulary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * *
     * String-encoded Content Vocabulary Proto
     * (Version 1.0.0-DRAFT)
     *
     * This vocabulary defided in JSON Schema Validation extension describe the format keyword defined to allow schema authors 
     * to convey syntactic information for a fixed subset of values which are accurately described by authoritative resources, be 
     * they RFCs or other external specifications
     *
     * Vocabulary url: 
     * -https://json-schema.org/draft/2020-12/meta/format-annotation
     *
     * Authors: 
     * - Andrea Gioia
     *
     * LICENCE: 
     * - Apache License Version 2.0 (https://github.com/opendatamesh-initiative/odm-specification-schema-annotations/blob/main/LICENSE)
     * </pre>
     *
     * Protobuf type {@code vcb.sec.ContentVocabulary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vcb.sec.ContentVocabulary)
        vcb.sec.V06ContentVocabulary.ContentVocabularyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vcb.sec.V06ContentVocabulary.internal_static_vcb_sec_ContentVocabulary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vcb.sec.V06ContentVocabulary.internal_static_vcb_sec_ContentVocabulary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vcb.sec.V06ContentVocabulary.ContentVocabulary.class, vcb.sec.V06ContentVocabulary.ContentVocabulary.Builder.class);
      }

      // Construct using vcb.sec.V06ContentVocabulary.ContentVocabulary.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        contentEncoding_ = "";
        contentMediaType_ = "";
        contentSchema_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vcb.sec.V06ContentVocabulary.internal_static_vcb_sec_ContentVocabulary_descriptor;
      }

      @java.lang.Override
      public vcb.sec.V06ContentVocabulary.ContentVocabulary getDefaultInstanceForType() {
        return vcb.sec.V06ContentVocabulary.ContentVocabulary.getDefaultInstance();
      }

      @java.lang.Override
      public vcb.sec.V06ContentVocabulary.ContentVocabulary build() {
        vcb.sec.V06ContentVocabulary.ContentVocabulary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vcb.sec.V06ContentVocabulary.ContentVocabulary buildPartial() {
        vcb.sec.V06ContentVocabulary.ContentVocabulary result = new vcb.sec.V06ContentVocabulary.ContentVocabulary(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(vcb.sec.V06ContentVocabulary.ContentVocabulary result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.contentEncoding_ = contentEncoding_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.contentMediaType_ = contentMediaType_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.contentSchema_ = contentSchema_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vcb.sec.V06ContentVocabulary.ContentVocabulary) {
          return mergeFrom((vcb.sec.V06ContentVocabulary.ContentVocabulary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vcb.sec.V06ContentVocabulary.ContentVocabulary other) {
        if (other == vcb.sec.V06ContentVocabulary.ContentVocabulary.getDefaultInstance()) return this;
        if (other.hasContentEncoding()) {
          contentEncoding_ = other.contentEncoding_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasContentMediaType()) {
          contentMediaType_ = other.contentMediaType_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasContentSchema()) {
          contentSchema_ = other.contentSchema_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 496002: {
                contentEncoding_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 496002
              case 496010: {
                contentMediaType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 496010
              case 496018: {
                contentSchema_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 496018
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object contentEncoding_ = "";
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the contentEncoding field is set.
       */
      public boolean hasContentEncoding() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
       * @return The contentEncoding.
       */
      public java.lang.String getContentEncoding() {
        java.lang.Object ref = contentEncoding_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentEncoding_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
       * @return The bytes for contentEncoding.
       */
      public com.google.protobuf.ByteString
          getContentEncodingBytes() {
        java.lang.Object ref = contentEncoding_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentEncoding_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The contentEncoding to set.
       * @return This builder for chaining.
       */
      public Builder setContentEncoding(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contentEncoding_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearContentEncoding() {
        contentEncoding_ = getDefaultInstance().getContentEncoding();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * - Keywords applicable to string properties
       * </pre>
       *
       * <code>optional string contentEncoding = 62000 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The bytes for contentEncoding to set.
       * @return This builder for chaining.
       */
      public Builder setContentEncodingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contentEncoding_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object contentMediaType_ = "";
      /**
       * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the contentMediaType field is set.
       */
      public boolean hasContentMediaType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
       * @return The contentMediaType.
       */
      public java.lang.String getContentMediaType() {
        java.lang.Object ref = contentMediaType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentMediaType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
       * @return The bytes for contentMediaType.
       */
      public com.google.protobuf.ByteString
          getContentMediaTypeBytes() {
        java.lang.Object ref = contentMediaType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentMediaType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The contentMediaType to set.
       * @return This builder for chaining.
       */
      public Builder setContentMediaType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contentMediaType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearContentMediaType() {
        contentMediaType_ = getDefaultInstance().getContentMediaType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentMediaType = 62001 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The bytes for contentMediaType to set.
       * @return This builder for chaining.
       */
      public Builder setContentMediaTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contentMediaType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object contentSchema_ = "";
      /**
       * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the contentSchema field is set.
       */
      public boolean hasContentSchema() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
       * @return The contentSchema.
       */
      public java.lang.String getContentSchema() {
        java.lang.Object ref = contentSchema_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentSchema_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
       * @return The bytes for contentSchema.
       */
      public com.google.protobuf.ByteString
          getContentSchemaBytes() {
        java.lang.Object ref = contentSchema_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentSchema_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The contentSchema to set.
       * @return This builder for chaining.
       */
      public Builder setContentSchema(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contentSchema_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearContentSchema() {
        contentSchema_ = getDefaultInstance().getContentSchema();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentSchema = 62002 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The bytes for contentSchema to set.
       * @return This builder for chaining.
       */
      public Builder setContentSchemaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contentSchema_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vcb.sec.ContentVocabulary)
    }

    // @@protoc_insertion_point(class_scope:vcb.sec.ContentVocabulary)
    private static final vcb.sec.V06ContentVocabulary.ContentVocabulary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vcb.sec.V06ContentVocabulary.ContentVocabulary();
    }

    public static vcb.sec.V06ContentVocabulary.ContentVocabulary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContentVocabulary>
        PARSER = new com.google.protobuf.AbstractParser<ContentVocabulary>() {
      @java.lang.Override
      public ContentVocabulary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ContentVocabulary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContentVocabulary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vcb.sec.V06ContentVocabulary.ContentVocabulary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SK_FIELD_NUMBER = 69997;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      vcb.sec.V06ContentVocabulary.ContentVocabulary> sk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.sec.V06ContentVocabulary.ContentVocabulary.class,
        vcb.sec.V06ContentVocabulary.ContentVocabulary.getDefaultInstance());
  public static final int MK_FIELD_NUMBER = 69998;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      vcb.sec.V06ContentVocabulary.ContentVocabulary> mk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.sec.V06ContentVocabulary.ContentVocabulary.class,
        vcb.sec.V06ContentVocabulary.ContentVocabulary.getDefaultInstance());
  public static final int FK_FIELD_NUMBER = 69999;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      vcb.sec.V06ContentVocabulary.ContentVocabulary> fk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.sec.V06ContentVocabulary.ContentVocabulary.class,
        vcb.sec.V06ContentVocabulary.ContentVocabulary.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vcb_sec_ContentVocabulary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcb_sec_ContentVocabulary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034v06-content-vocabulary.proto\022\007vcb.sec\032" +
      " google/protobuf/descriptor.proto\"\274\001\n\021Co" +
      "ntentVocabulary\022#\n\017contentEncoding\030\260\344\003 \001" +
      "(\tB\003\230\001\004H\000\210\001\001\022$\n\020contentMediaType\030\261\344\003 \001(\t" +
      "B\003\230\001\004H\001\210\001\001\022!\n\rcontentSchema\030\262\344\003 \001(\tB\003\230\001\004" +
      "H\002\210\001\001B\022\n\020_contentEncodingB\023\n\021_contentMed" +
      "iaTypeB\020\n\016_contentSchema:F\n\002sk\022\034.google." +
      "protobuf.FileOptions\030\355\242\004 \001(\0132\032.vcb.sec.C" +
      "ontentVocabulary:I\n\002mk\022\037.google.protobuf" +
      ".MessageOptions\030\356\242\004 \001(\0132\032.vcb.sec.Conten" +
      "tVocabulary:G\n\002fk\022\035.google.protobuf.Fiel" +
      "dOptions\030\357\242\004 \001(\0132\032.vcb.sec.ContentVocabu" +
      "laryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_vcb_sec_ContentVocabulary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vcb_sec_ContentVocabulary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vcb_sec_ContentVocabulary_descriptor,
        new java.lang.String[] { "ContentEncoding", "ContentMediaType", "ContentSchema", });
    sk.internalInit(descriptor.getExtensions().get(0));
    mk.internalInit(descriptor.getExtensions().get(1));
    fk.internalInit(descriptor.getExtensions().get(2));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
