// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v08-context-syntactic-vocabulary.proto
// Protobuf Java Version: 4.29.3

package vcb.syn;

public final class V08ContextSyntacticVocabulary {
  private V08ContextSyntacticVocabulary() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      V08ContextSyntacticVocabulary.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(vcb.syn.V08ContextSyntacticVocabulary.sk);
    registry.add(vcb.syn.V08ContextSyntacticVocabulary.mk);
    registry.add(vcb.syn.V08ContextSyntacticVocabulary.fk);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyntacticContextVocabularyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vcb.syn.SyntacticContextVocabulary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Keywords applicable only to properties (starting from x6000 )
     * </pre>
     *
     * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the conformsTo field is set.
     */
    boolean hasConformsTo();
    /**
     * <pre>
     * Keywords applicable only to properties (starting from x6000 )
     * </pre>
     *
     * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The conformsTo.
     */
    java.lang.String getConformsTo();
    /**
     * <pre>
     * Keywords applicable only to properties (starting from x6000 )
     * </pre>
     *
     * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for conformsTo.
     */
    com.google.protobuf.ByteString
        getConformsToBytes();
  }
  /**
   * <pre>
   * *
   * Syntactic Context Annotations Vocabulary Proto
   * (Version 1.0.0-DRAFT)
   *
   * The Syntactic Context Annotations Vocabulary, defined as an extension of the SAS, provides commonly used metadata to 
   * syntactly contextualize schema element.
   *
   * Vocabulary url: 
   * - https://dpds.opendatamesh.org/specifications/sas/1.0.0-DRAFT/vocab/context-syntactic
   *
   * Authors: 
   * - Andrea Gioia
   *
   * LICENCE: 
   * - Apache License Version 2.0 (https://github.com/opendatamesh-initiative/odm-specification-schema-annotations/blob/main/LICENSE)
   * </pre>
   *
   * Protobuf type {@code vcb.syn.SyntacticContextVocabulary}
   */
  public static final class SyntacticContextVocabulary extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vcb.syn.SyntacticContextVocabulary)
      SyntacticContextVocabularyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        SyntacticContextVocabulary.class.getName());
    }
    // Use SyntacticContextVocabulary.newBuilder() to construct.
    private SyntacticContextVocabulary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SyntacticContextVocabulary() {
      conformsTo_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vcb.syn.V08ContextSyntacticVocabulary.internal_static_vcb_syn_SyntacticContextVocabulary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vcb.syn.V08ContextSyntacticVocabulary.internal_static_vcb_syn_SyntacticContextVocabulary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.class, vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.Builder.class);
    }

    private int bitField0_;
    public static final int CONFORMSTO_FIELD_NUMBER = 86000;
    @SuppressWarnings("serial")
    private volatile java.lang.Object conformsTo_ = "";
    /**
     * <pre>
     * Keywords applicable only to properties (starting from x6000 )
     * </pre>
     *
     * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
     * @return Whether the conformsTo field is set.
     */
    @java.lang.Override
    public boolean hasConformsTo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Keywords applicable only to properties (starting from x6000 )
     * </pre>
     *
     * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The conformsTo.
     */
    @java.lang.Override
    public java.lang.String getConformsTo() {
      java.lang.Object ref = conformsTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conformsTo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Keywords applicable only to properties (starting from x6000 )
     * </pre>
     *
     * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
     * @return The bytes for conformsTo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConformsToBytes() {
      java.lang.Object ref = conformsTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conformsTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 86000, conformsTo_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(86000, conformsTo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary)) {
        return super.equals(obj);
      }
      vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary other = (vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary) obj;

      if (hasConformsTo() != other.hasConformsTo()) return false;
      if (hasConformsTo()) {
        if (!getConformsTo()
            .equals(other.getConformsTo())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConformsTo()) {
        hash = (37 * hash) + CONFORMSTO_FIELD_NUMBER;
        hash = (53 * hash) + getConformsTo().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * *
     * Syntactic Context Annotations Vocabulary Proto
     * (Version 1.0.0-DRAFT)
     *
     * The Syntactic Context Annotations Vocabulary, defined as an extension of the SAS, provides commonly used metadata to 
     * syntactly contextualize schema element.
     *
     * Vocabulary url: 
     * - https://dpds.opendatamesh.org/specifications/sas/1.0.0-DRAFT/vocab/context-syntactic
     *
     * Authors: 
     * - Andrea Gioia
     *
     * LICENCE: 
     * - Apache License Version 2.0 (https://github.com/opendatamesh-initiative/odm-specification-schema-annotations/blob/main/LICENSE)
     * </pre>
     *
     * Protobuf type {@code vcb.syn.SyntacticContextVocabulary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vcb.syn.SyntacticContextVocabulary)
        vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabularyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vcb.syn.V08ContextSyntacticVocabulary.internal_static_vcb_syn_SyntacticContextVocabulary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vcb.syn.V08ContextSyntacticVocabulary.internal_static_vcb_syn_SyntacticContextVocabulary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.class, vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.Builder.class);
      }

      // Construct using vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        conformsTo_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vcb.syn.V08ContextSyntacticVocabulary.internal_static_vcb_syn_SyntacticContextVocabulary_descriptor;
      }

      @java.lang.Override
      public vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary getDefaultInstanceForType() {
        return vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.getDefaultInstance();
      }

      @java.lang.Override
      public vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary build() {
        vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary buildPartial() {
        vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary result = new vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.conformsTo_ = conformsTo_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary) {
          return mergeFrom((vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary other) {
        if (other == vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.getDefaultInstance()) return this;
        if (other.hasConformsTo()) {
          conformsTo_ = other.conformsTo_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 688002: {
                conformsTo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 688002
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object conformsTo_ = "";
      /**
       * <pre>
       * Keywords applicable only to properties (starting from x6000 )
       * </pre>
       *
       * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
       * @return Whether the conformsTo field is set.
       */
      public boolean hasConformsTo() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Keywords applicable only to properties (starting from x6000 )
       * </pre>
       *
       * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
       * @return The conformsTo.
       */
      public java.lang.String getConformsTo() {
        java.lang.Object ref = conformsTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          conformsTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Keywords applicable only to properties (starting from x6000 )
       * </pre>
       *
       * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
       * @return The bytes for conformsTo.
       */
      public com.google.protobuf.ByteString
          getConformsToBytes() {
        java.lang.Object ref = conformsTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conformsTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Keywords applicable only to properties (starting from x6000 )
       * </pre>
       *
       * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The conformsTo to set.
       * @return This builder for chaining.
       */
      public Builder setConformsTo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        conformsTo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Keywords applicable only to properties (starting from x6000 )
       * </pre>
       *
       * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
       * @return This builder for chaining.
       */
      public Builder clearConformsTo() {
        conformsTo_ = getDefaultInstance().getConformsTo();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Keywords applicable only to properties (starting from x6000 )
       * </pre>
       *
       * <code>optional string conformsTo = 86000 [targets = TARGET_TYPE_FIELD];</code>
       * @param value The bytes for conformsTo to set.
       * @return This builder for chaining.
       */
      public Builder setConformsToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        conformsTo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vcb.syn.SyntacticContextVocabulary)
    }

    // @@protoc_insertion_point(class_scope:vcb.syn.SyntacticContextVocabulary)
    private static final vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary();
    }

    public static vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyntacticContextVocabulary>
        PARSER = new com.google.protobuf.AbstractParser<SyntacticContextVocabulary>() {
      @java.lang.Override
      public SyntacticContextVocabulary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SyntacticContextVocabulary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyntacticContextVocabulary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SK_FIELD_NUMBER = 89997;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary> sk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.class,
        vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.getDefaultInstance());
  public static final int MK_FIELD_NUMBER = 89998;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary> mk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.class,
        vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.getDefaultInstance());
  public static final int FK_FIELD_NUMBER = 89999;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary> fk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.class,
        vcb.syn.V08ContextSyntacticVocabulary.SyntacticContextVocabulary.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vcb_syn_SyntacticContextVocabulary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcb_syn_SyntacticContextVocabulary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&v08-context-syntactic-vocabulary.proto" +
      "\022\007vcb.syn\032 google/protobuf/descriptor.pr" +
      "oto\"K\n\032SyntacticContextVocabulary\022\036\n\ncon" +
      "formsTo\030\360\237\005 \001(\tB\003\230\001\004H\000\210\001\001B\r\n\013_conformsTo" +
      ":O\n\002sk\022\034.google.protobuf.FileOptions\030\215\277\005" +
      " \001(\0132#.vcb.syn.SyntacticContextVocabular" +
      "y:R\n\002mk\022\037.google.protobuf.MessageOptions" +
      "\030\216\277\005 \001(\0132#.vcb.syn.SyntacticContextVocab" +
      "ulary:P\n\002fk\022\035.google.protobuf.FieldOptio" +
      "ns\030\217\277\005 \001(\0132#.vcb.syn.SyntacticContextVoc" +
      "abularyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_vcb_syn_SyntacticContextVocabulary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vcb_syn_SyntacticContextVocabulary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vcb_syn_SyntacticContextVocabulary_descriptor,
        new java.lang.String[] { "ConformsTo", });
    sk.internalInit(descriptor.getExtensions().get(0));
    mk.internalInit(descriptor.getExtensions().get(1));
    fk.internalInit(descriptor.getExtensions().get(2));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
