// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v01-sas-core-vocabulary.proto
// Protobuf Java Version: 4.29.3

package vcb.sas;

public final class V01SasCoreVocabulary {
  private V01SasCoreVocabulary() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      V01SasCoreVocabulary.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(vcb.sas.V01SasCoreVocabulary.sk);
    registry.add(vcb.sas.V01SasCoreVocabulary.mk);
    registry.add(vcb.sas.V01SasCoreVocabulary.fk);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SasCoreVocabularyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vcb.sas.SasCoreVocabulary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Keywords applicable only to schema and objects (starting from x2300)
     * </pre>
     *
     * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
     * @return Whether the sas field is set.
     */
    boolean hasSas();
    /**
     * <pre>
     * Keywords applicable only to schema and objects (starting from x2300)
     * </pre>
     *
     * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
     * @return The sas.
     */
    java.lang.String getSas();
    /**
     * <pre>
     * Keywords applicable only to schema and objects (starting from x2300)
     * </pre>
     *
     * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
     * @return The bytes for sas.
     */
    com.google.protobuf.ByteString
        getSasBytes();

    /**
     * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
     * @return Whether the sasDialect field is set.
     */
    boolean hasSasDialect();
    /**
     * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
     * @return The sasDialect.
     */
    java.lang.String getSasDialect();
    /**
     * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
     * @return The bytes for sasDialect.
     */
    com.google.protobuf.ByteString
        getSasDialectBytes();

    /**
     * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
     * @return Whether the sasSchemaId field is set.
     */
    boolean hasSasSchemaId();
    /**
     * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
     * @return The sasSchemaId.
     */
    java.lang.String getSasSchemaId();
    /**
     * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
     * @return The bytes for sasSchemaId.
     */
    com.google.protobuf.ByteString
        getSasSchemaIdBytes();
  }
  /**
   * Protobuf type {@code vcb.sas.SasCoreVocabulary}
   */
  public static final class SasCoreVocabulary extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vcb.sas.SasCoreVocabulary)
      SasCoreVocabularyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        SasCoreVocabulary.class.getName());
    }
    // Use SasCoreVocabulary.newBuilder() to construct.
    private SasCoreVocabulary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SasCoreVocabulary() {
      sas_ = "";
      sasDialect_ = "";
      sasSchemaId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return vcb.sas.V01SasCoreVocabulary.internal_static_vcb_sas_SasCoreVocabulary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return vcb.sas.V01SasCoreVocabulary.internal_static_vcb_sas_SasCoreVocabulary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.class, vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.Builder.class);
    }

    private int bitField0_;
    public static final int SAS_FIELD_NUMBER = 10001;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sas_ = "";
    /**
     * <pre>
     * Keywords applicable only to schema and objects (starting from x2300)
     * </pre>
     *
     * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
     * @return Whether the sas field is set.
     */
    @java.lang.Override
    public boolean hasSas() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Keywords applicable only to schema and objects (starting from x2300)
     * </pre>
     *
     * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
     * @return The sas.
     */
    @java.lang.Override
    public java.lang.String getSas() {
      java.lang.Object ref = sas_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sas_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Keywords applicable only to schema and objects (starting from x2300)
     * </pre>
     *
     * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
     * @return The bytes for sas.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSasBytes() {
      java.lang.Object ref = sas_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sas_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SASDIALECT_FIELD_NUMBER = 10002;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sasDialect_ = "";
    /**
     * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
     * @return Whether the sasDialect field is set.
     */
    @java.lang.Override
    public boolean hasSasDialect() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
     * @return The sasDialect.
     */
    @java.lang.Override
    public java.lang.String getSasDialect() {
      java.lang.Object ref = sasDialect_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sasDialect_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
     * @return The bytes for sasDialect.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSasDialectBytes() {
      java.lang.Object ref = sasDialect_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sasDialect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SASSCHEMAID_FIELD_NUMBER = 10003;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sasSchemaId_ = "";
    /**
     * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
     * @return Whether the sasSchemaId field is set.
     */
    @java.lang.Override
    public boolean hasSasSchemaId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
     * @return The sasSchemaId.
     */
    @java.lang.Override
    public java.lang.String getSasSchemaId() {
      java.lang.Object ref = sasSchemaId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sasSchemaId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
     * @return The bytes for sasSchemaId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSasSchemaIdBytes() {
      java.lang.Object ref = sasSchemaId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sasSchemaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10001, sas_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10002, sasDialect_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10003, sasSchemaId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10001, sas_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10002, sasDialect_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10003, sasSchemaId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary)) {
        return super.equals(obj);
      }
      vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary other = (vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary) obj;

      if (hasSas() != other.hasSas()) return false;
      if (hasSas()) {
        if (!getSas()
            .equals(other.getSas())) return false;
      }
      if (hasSasDialect() != other.hasSasDialect()) return false;
      if (hasSasDialect()) {
        if (!getSasDialect()
            .equals(other.getSasDialect())) return false;
      }
      if (hasSasSchemaId() != other.hasSasSchemaId()) return false;
      if (hasSasSchemaId()) {
        if (!getSasSchemaId()
            .equals(other.getSasSchemaId())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSas()) {
        hash = (37 * hash) + SAS_FIELD_NUMBER;
        hash = (53 * hash) + getSas().hashCode();
      }
      if (hasSasDialect()) {
        hash = (37 * hash) + SASDIALECT_FIELD_NUMBER;
        hash = (53 * hash) + getSasDialect().hashCode();
      }
      if (hasSasSchemaId()) {
        hash = (37 * hash) + SASSCHEMAID_FIELD_NUMBER;
        hash = (53 * hash) + getSasSchemaId().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vcb.sas.SasCoreVocabulary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vcb.sas.SasCoreVocabulary)
        vcb.sas.V01SasCoreVocabulary.SasCoreVocabularyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return vcb.sas.V01SasCoreVocabulary.internal_static_vcb_sas_SasCoreVocabulary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return vcb.sas.V01SasCoreVocabulary.internal_static_vcb_sas_SasCoreVocabulary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.class, vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.Builder.class);
      }

      // Construct using vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sas_ = "";
        sasDialect_ = "";
        sasSchemaId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return vcb.sas.V01SasCoreVocabulary.internal_static_vcb_sas_SasCoreVocabulary_descriptor;
      }

      @java.lang.Override
      public vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary getDefaultInstanceForType() {
        return vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.getDefaultInstance();
      }

      @java.lang.Override
      public vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary build() {
        vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary buildPartial() {
        vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary result = new vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sas_ = sas_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sasDialect_ = sasDialect_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sasSchemaId_ = sasSchemaId_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary) {
          return mergeFrom((vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary other) {
        if (other == vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.getDefaultInstance()) return this;
        if (other.hasSas()) {
          sas_ = other.sas_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasSasDialect()) {
          sasDialect_ = other.sasDialect_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasSasSchemaId()) {
          sasSchemaId_ = other.sasSchemaId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 80010: {
                sas_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 80010
              case 80018: {
                sasDialect_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 80018
              case 80026: {
                sasSchemaId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 80026
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object sas_ = "";
      /**
       * <pre>
       * Keywords applicable only to schema and objects (starting from x2300)
       * </pre>
       *
       * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
       * @return Whether the sas field is set.
       */
      public boolean hasSas() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Keywords applicable only to schema and objects (starting from x2300)
       * </pre>
       *
       * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
       * @return The sas.
       */
      public java.lang.String getSas() {
        java.lang.Object ref = sas_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sas_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Keywords applicable only to schema and objects (starting from x2300)
       * </pre>
       *
       * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
       * @return The bytes for sas.
       */
      public com.google.protobuf.ByteString
          getSasBytes() {
        java.lang.Object ref = sas_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sas_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Keywords applicable only to schema and objects (starting from x2300)
       * </pre>
       *
       * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
       * @param value The sas to set.
       * @return This builder for chaining.
       */
      public Builder setSas(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sas_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Keywords applicable only to schema and objects (starting from x2300)
       * </pre>
       *
       * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
       * @return This builder for chaining.
       */
      public Builder clearSas() {
        sas_ = getDefaultInstance().getSas();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Keywords applicable only to schema and objects (starting from x2300)
       * </pre>
       *
       * <code>optional string sas = 10001 [targets = TARGET_TYPE_FILE];</code>
       * @param value The bytes for sas to set.
       * @return This builder for chaining.
       */
      public Builder setSasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sas_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object sasDialect_ = "";
      /**
       * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
       * @return Whether the sasDialect field is set.
       */
      public boolean hasSasDialect() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
       * @return The sasDialect.
       */
      public java.lang.String getSasDialect() {
        java.lang.Object ref = sasDialect_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sasDialect_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
       * @return The bytes for sasDialect.
       */
      public com.google.protobuf.ByteString
          getSasDialectBytes() {
        java.lang.Object ref = sasDialect_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sasDialect_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
       * @param value The sasDialect to set.
       * @return This builder for chaining.
       */
      public Builder setSasDialect(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sasDialect_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
       * @return This builder for chaining.
       */
      public Builder clearSasDialect() {
        sasDialect_ = getDefaultInstance().getSasDialect();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string sasDialect = 10002 [targets = TARGET_TYPE_FILE];</code>
       * @param value The bytes for sasDialect to set.
       * @return This builder for chaining.
       */
      public Builder setSasDialectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sasDialect_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object sasSchemaId_ = "";
      /**
       * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
       * @return Whether the sasSchemaId field is set.
       */
      public boolean hasSasSchemaId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
       * @return The sasSchemaId.
       */
      public java.lang.String getSasSchemaId() {
        java.lang.Object ref = sasSchemaId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sasSchemaId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
       * @return The bytes for sasSchemaId.
       */
      public com.google.protobuf.ByteString
          getSasSchemaIdBytes() {
        java.lang.Object ref = sasSchemaId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sasSchemaId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
       * @param value The sasSchemaId to set.
       * @return This builder for chaining.
       */
      public Builder setSasSchemaId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sasSchemaId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
       * @return This builder for chaining.
       */
      public Builder clearSasSchemaId() {
        sasSchemaId_ = getDefaultInstance().getSasSchemaId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string sasSchemaId = 10003 [targets = TARGET_TYPE_FILE];</code>
       * @param value The bytes for sasSchemaId to set.
       * @return This builder for chaining.
       */
      public Builder setSasSchemaIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sasSchemaId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vcb.sas.SasCoreVocabulary)
    }

    // @@protoc_insertion_point(class_scope:vcb.sas.SasCoreVocabulary)
    private static final vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary();
    }

    public static vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SasCoreVocabulary>
        PARSER = new com.google.protobuf.AbstractParser<SasCoreVocabulary>() {
      @java.lang.Override
      public SasCoreVocabulary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SasCoreVocabulary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SasCoreVocabulary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SK_FIELD_NUMBER = 18997;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary> sk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.class,
        vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.getDefaultInstance());
  public static final int MK_FIELD_NUMBER = 18998;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary> mk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.class,
        vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.getDefaultInstance());
  public static final int FK_FIELD_NUMBER = 18999;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary> fk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.class,
        vcb.sas.V01SasCoreVocabulary.SasCoreVocabulary.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vcb_sas_SasCoreVocabulary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vcb_sas_SasCoreVocabulary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035v01-sas-core-vocabulary.proto\022\007vcb.sas" +
      "\032 google/protobuf/descriptor.proto\"\221\001\n\021S" +
      "asCoreVocabulary\022\026\n\003sas\030\221N \001(\tB\003\230\001\001H\000\210\001\001" +
      "\022\035\n\nsasDialect\030\222N \001(\tB\003\230\001\001H\001\210\001\001\022\036\n\013sasSc" +
      "hemaId\030\223N \001(\tB\003\230\001\001H\002\210\001\001B\006\n\004_sasB\r\n\013_sasD" +
      "ialectB\016\n\014_sasSchemaId:F\n\002sk\022\034.google.pr" +
      "otobuf.FileOptions\030\265\224\001 \001(\0132\032.vcb.sas.Sas" +
      "CoreVocabulary:I\n\002mk\022\037.google.protobuf.M" +
      "essageOptions\030\266\224\001 \001(\0132\032.vcb.sas.SasCoreV" +
      "ocabulary:G\n\002fk\022\035.google.protobuf.FieldO" +
      "ptions\030\267\224\001 \001(\0132\032.vcb.sas.SasCoreVocabula" +
      "ryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_vcb_sas_SasCoreVocabulary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vcb_sas_SasCoreVocabulary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vcb_sas_SasCoreVocabulary_descriptor,
        new java.lang.String[] { "Sas", "SasDialect", "SasSchemaId", });
    sk.internalInit(descriptor.getExtensions().get(0));
    mk.internalInit(descriptor.getExtensions().get(1));
    fk.internalInit(descriptor.getExtensions().get(2));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
